// GENERATED — do not edit by hand. Categories audited against Wikipedia
// short descriptions by scripts/audit-categories.mjs.

export const extra = [
  { word: 'ananas', wiki: 'Ananas', category: 'Food', article: 'an', common: false },
  { word: 'bilberry', wiki: 'Bilberry', category: 'Food', common: false },
  { word: 'biriba', wiki: 'Biriba', category: 'Food', common: false },
  { word: 'calabash', wiki: 'Calabash', category: 'Nature', common: false },
  { word: 'calamansi', wiki: 'Calamansi', category: 'Food', common: false },
  { word: 'cherimoya', wiki: 'Cherimoya', category: 'Food', common: false },
  { word: 'citrange', wiki: 'Citrange', category: 'Food', common: false },
  { word: 'citron', wiki: 'Citron', category: 'Nature', common: false },
  { word: 'clingstone', wiki: 'Clingstone', category: 'Nature', common: false },
  { word: 'damson', wiki: 'Damson', category: 'Food', common: false },
  { word: 'durian', wiki: 'Durian', category: 'Food', common: false },
  { word: 'eggplant', wiki: 'Eggplant', category: 'Nature', article: 'an', common: false },
  { word: 'feijoa', wiki: 'Feijoa', category: 'Nature', common: false },
  { word: 'greengage', wiki: 'Greengage', category: 'Food', common: false },
  { word: 'guarana', wiki: 'Guarana', category: 'Nature', common: false },
  { word: 'jujube', wiki: 'Jujube', category: 'Food', common: false },
  { word: 'kumquat', wiki: 'Kumquat', category: 'Food', common: false },
  { word: 'limequat', wiki: 'Limequat', category: 'Food', common: false },
  { word: 'loquat', wiki: 'Loquat', category: 'Nature', common: false },
  { word: 'mangosteen', wiki: 'Mangosteen', category: 'Food', common: false },
  { word: 'pimiento', wiki: 'Pimiento', category: 'Food', common: false },
  { word: 'pomelo', wiki: 'Pomelo', category: 'Food', common: false },
  { word: 'pulasan', wiki: 'Pulasan', category: 'Food', common: false },
  { word: 'quince', wiki: 'Quince', category: 'Food', common: false },
  { word: 'rambutan', wiki: 'Rambutan', category: 'Food', common: false },
  { word: 'soursop', wiki: 'Soursop', category: 'Food', common: false },
  { word: 'tangelo', wiki: 'Tangelo', category: 'Food', common: false },
  { word: 'zucchini', wiki: 'Zucchini', category: 'Food', common: false },
  { word: 'arrowroot', wiki: 'Arrowroot', category: 'Food', article: 'an', common: false },
  { word: 'cardoon', wiki: 'Cardoon', category: 'Nature', common: false },
  { word: 'celeriac', wiki: 'Celeriac', category: 'Nature', common: false },
  { word: 'celtuce', wiki: 'Celtuce', category: 'Food', common: false },
  { word: 'chard', wiki: 'Chard', category: 'Food', common: false },
  { word: 'chayote', wiki: 'Chayote', category: 'Food', common: false },
  { word: 'daikon', wiki: 'Daikon', category: 'Nature', common: false },
  { word: 'endive', wiki: 'Endive', category: 'Food', article: 'an', common: false },
  { word: 'fiddlehead', wiki: 'Fiddlehead', category: 'Food', common: false },
  { word: 'gilo', wiki: 'Gilo', category: 'Food', common: false },
  { word: 'guar', wiki: 'Guar', category: 'Nature', common: false },
  { word: 'kohlrabi', wiki: 'Kohlrabi', category: 'Food', common: false },
  { word: 'maize', wiki: 'Maize', category: 'Food', common: false },
  { word: 'nopal', wiki: 'Nopal', category: 'Food', common: false },
  { word: 'rutabaga', wiki: 'Rutabaga', category: 'Food', common: false },
  { word: 'scallion', wiki: 'Scallion', category: 'Food', common: false },
  { word: 'solanum', wiki: 'Solanum', category: 'Food', common: false },
  { word: 'sorrel', wiki: 'Sorrel', category: 'Nature', common: false },
  { word: 'taro', wiki: 'Taro', category: 'Nature', common: false },
  { word: 'tomatillo', wiki: 'Tomatillo', category: 'Nature', common: false },
  { word: 'vegetable', wiki: 'Vegetable', category: 'Food', common: false },
  { word: 'barmbrack', wiki: 'Barmbrack', category: 'Food', common: false },
  { word: 'breadbox', wiki: 'Breadbox', category: 'Food', common: false },
  { word: 'challah', wiki: 'Challah', category: 'Food', common: false },
  { word: 'ficelle', wiki: 'Ficelle', category: 'Food', common: false },
  { word: 'kisra', wiki: 'Kisra', category: 'Food', common: false },
  { word: 'manchet', wiki: 'Manchet', category: 'Food', common: false },
  { word: 'piki', wiki: 'Piki', category: 'Food', common: false },
  { word: 'pita', wiki: 'Pita', category: 'Food', common: false },
  { word: 'pumpernickel', wiki: 'Pumpernickel', category: 'Food', common: false },
  { word: 'rusk', wiki: 'Rusk', category: 'Food', common: false },
  { word: 'ambrosia', wiki: 'Ambrosia', category: 'Food', article: 'an', common: false },
  { word: 'blancmange', wiki: 'Blancmange', category: 'Food', common: false },
  { word: 'compote', wiki: 'Compote', category: 'Food', common: false },
  { word: 'confiture', wiki: 'Confiture', category: 'Food', common: false },
  { word: 'crumble', wiki: 'Crumble', category: 'Food', common: false },
  { word: 'dariole', wiki: 'Dariole', category: 'Food', common: false },
  { word: 'dessert', wiki: 'Dessert', category: 'Food', common: false },
  { word: 'halo-halo', wiki: 'Halo-halo', category: 'Food', common: false },
  { word: 'mess', wiki: 'Mess', category: 'Food', common: false },
  { word: 'mousse', wiki: 'Mousse', category: 'Food', common: false },
  { word: 'parfait', wiki: 'Parfait', category: 'Food', common: false },
  { word: 'snowball', wiki: 'Snowball', category: 'Food', common: false },
  { word: 'sundae', wiki: 'Sundae', category: 'Food', common: false },
  { word: 'caciocavallo', wiki: 'Caciocavallo', category: 'Food', common: false },
  { word: 'camembert', wiki: 'Camembert', category: 'Food', common: false },
  { word: 'gloucester', wiki: 'Gloucester', category: 'Food', common: false },
  { word: 'gorgonzola', wiki: 'Gorgonzola', category: 'Food', common: false },
  { word: 'bird', wiki: 'Bird', category: 'Animals', common: false },
  { word: 'carpometacarpus', wiki: 'Carpometacarpus', category: 'Body', common: false },
  { word: 'cuckoo-roller', wiki: 'Cuckoo-roller', category: 'Animals', common: false },
  { word: 'hoatzin', wiki: 'Hoatzin', category: 'Animals', common: false },
  { word: 'juvenal', wiki: 'Juvenal', category: 'Animals', common: false },
  { word: 'kagu', wiki: 'Kagu', category: 'Animals', common: false },
  { word: 'mousebird', wiki: 'Mousebird', category: 'Animals', common: false },
  { word: 'oilbird', wiki: 'Oilbird', category: 'Animals', article: 'an', common: false },
  { word: 'owlet-nightjar', wiki: 'Owlet-nightjar', category: 'Animals', article: 'an', common: false },
  { word: 'potoo', wiki: 'Potoo', category: 'Animals', common: false },
  { word: 'quetzal', wiki: 'Quetzal', category: 'Animals', common: false },
  { word: 'seriema', wiki: 'Seriema', category: 'Animals', common: false },
  { word: 'songbird', wiki: 'Songbird', category: 'Animals', common: false },
  { word: 'synsacrum', wiki: 'Synsacrum', category: 'Places', common: false },
  { word: 'trogon', wiki: 'Trogon', category: 'Animals', common: false },
  { word: 'wader', wiki: 'Wader', category: 'Animals', common: false },
  { word: 'deinotherium', wiki: 'Deinotherium', category: 'Animals', common: false },
  { word: 'mammal', wiki: 'Mammal', category: 'Animals', common: false },
  { word: 'bandfish', wiki: 'Bandfish', category: 'Animals', common: false },
  { word: 'bichir', wiki: 'Bichir', category: 'Animals', common: false },
  { word: 'cladodont', wiki: 'Cladodont', category: 'Animals', common: false },
  { word: 'cusk-eel', wiki: 'Cusk-eel', category: 'Animals', common: false },
  { word: 'foxfish', wiki: 'Foxfish', category: 'Animals', common: false },
  { word: 'frogfish', wiki: 'Frogfish', category: 'Animals', common: false },
  { word: 'grenadier', wiki: 'Grenadier', category: 'Animals', common: false },
  { word: 'isinglass', wiki: 'Isinglass', category: 'Animals', article: 'an', common: false },
  { word: 'longfin', wiki: 'Longfin', category: 'Animals', common: false },
  { word: 'mugil', wiki: 'Mugil', category: 'Animals', common: false },
  { word: 'redfish', wiki: 'Redfish', category: 'Animals', common: false },
  { word: 'roe', wiki: 'Roe', category: 'Animals', common: false },
  { word: 'silverfish', wiki: 'Silverfish', category: 'Animals', common: false },
  { word: 'stockfish', wiki: 'Stockfish', category: 'Animals', common: false },
  { word: 'viperfish', wiki: 'Viperfish', category: 'Animals', common: false },
  { word: 'wagtail', wiki: 'Wagtail', category: 'Animals', common: false },
  { word: 'whitebait', wiki: 'Whitebait', category: 'Animals', common: false },
  { word: 'bookworm', wiki: 'Bookworm', category: 'Animals', common: false },
  { word: 'cercus', wiki: 'Cercus', category: 'Animals', common: false },
  { word: 'firebrat', wiki: 'Firebrat', category: 'Animals', common: false },
  { word: 'gallinipper', wiki: 'Gallinipper', category: 'Nature', common: false },
  { word: 'incubus', wiki: 'Incubus', category: 'Animals', article: 'an', common: false },
  { word: 'insect', wiki: 'Insect', category: 'Animals', article: 'an', common: false },
  { word: 'nymph', wiki: 'Nymph', category: 'Animals', common: false },
  { word: 'stylops', wiki: 'Stylops', category: 'Animals', common: false },
  { word: 'thrips', wiki: 'Thrips', category: 'Animals', common: false },
  { word: 'anapsid', wiki: 'Anapsid', category: 'Animals', article: 'an', common: false },
  { word: 'diapsid', wiki: 'Diapsid', category: 'Animals', common: false },
  { word: 'dragon', wiki: 'Dragon', category: 'Animals', common: false },
  { word: 'aiguillette', wiki: 'Aiguillette', category: 'Clothes', article: 'an', common: false },
  { word: 'almuce', wiki: 'Almuce', category: 'Clothes', article: 'an', common: false },
  { word: 'amice', wiki: 'Amice', category: 'Clothes', article: 'an', common: false },
  { word: 'armscye', wiki: 'Armscye', category: 'Clothes', article: 'an', common: false },
  { word: 'baldric', wiki: 'Baldric', category: 'Home', common: false },
  { word: 'bathrobe', wiki: 'Bathrobe', category: 'Clothes', common: false },
  { word: 'bedgown', wiki: 'Bedgown', category: 'Clothes', common: false },
  { word: 'bloomers', wiki: 'Bloomers', category: 'Clothes', common: false },
  { word: 'bluecoat', wiki: 'Bluecoat', category: 'Clothes', common: false },
  { word: 'bodice', wiki: 'Bodice', category: 'Clothes', common: false },
  { word: 'bomber', wiki: 'Bomber', category: 'Vehicles', common: false },
  { word: 'bootee', wiki: 'Bootee', category: 'Clothes', common: false },
  { word: 'boothose', wiki: 'Boothose', category: 'Clothes', common: false },
  { word: 'breeches', wiki: 'Breeches', category: 'Clothes', common: false },
  { word: 'bustle', wiki: 'Bustle', category: 'Clothes', common: false },
  { word: 'camisole', wiki: 'Camisole', category: 'Clothes', common: false },
  { word: 'carmagnole', wiki: 'Carmagnole', category: 'Clothes', common: false },
  { word: 'cassock', wiki: 'Cassock', category: 'Clothes', common: false },
  { word: 'cestus', wiki: 'Cestus', category: 'Clothes', common: false },
  { word: 'chemise', wiki: 'Chemise', category: 'Clothes', common: false },
  { word: 'chemisette', wiki: 'Chemisette', category: 'Clothes', common: false },
  { word: 'chiton', wiki: 'Chiton', category: 'Clothes', common: false },
  { word: 'cilice', wiki: 'Cilice', category: 'Clothes', common: false },
  { word: 'clothing', wiki: 'Clothing', category: 'Clothes', common: false },
  { word: 'clutch', wiki: 'Clutch', category: 'Clothes', common: false },
  { word: 'codpiece', wiki: 'Codpiece', category: 'Clothes', common: false },
  { word: 'corsage', wiki: 'Corsage', category: 'Clothes', common: false },
  { word: 'cover-up', wiki: 'Cover-up', category: 'Clothes', common: false },
  { word: 'culottes', wiki: 'Culottes', category: 'Clothes', common: false },
  { word: 'delia', wiki: 'Delia', category: 'Clothes', common: false },
  { word: 'diaper', wiki: 'Diaper', category: 'Clothes', common: false },
  { word: 'dirndl', wiki: 'Dirndl', category: 'Clothes', common: false },
  { word: 'double-breasted', wiki: 'Double-breasted', category: 'Clothes', common: false },
  { word: 'dreadnought', wiki: 'Dreadnought', category: 'Clothes', common: false },
  { word: 'dressmaker', wiki: 'Dressmaker', category: 'Clothes', common: false },
  { word: 'dress-up', wiki: 'Dress-up', category: 'Clothes', common: false },
  { word: 'farthingale', wiki: 'Farthingale', category: 'Places', common: false },
  { word: 'fascinator', wiki: 'Fascinator', category: 'Clothes', common: false },
  { word: 'flannel', wiki: 'Flannel', category: 'Clothes', common: false },
  { word: 'fontange', wiki: 'Fontange', category: 'Clothes', common: false },
  { word: 'footwear', wiki: 'Footwear', category: 'Clothes', common: false },
  { word: 'foulard', wiki: 'Foulard', category: 'Clothes', common: false },
  { word: 'frock', wiki: 'Frock', category: 'Clothes', common: false },
  { word: 'fustanella', wiki: 'Fustanella', category: 'Clothes', common: false },
  { word: 'gabardine', wiki: 'Gabardine', category: 'Clothes', common: false },
  { word: 'garter', wiki: 'Garter', category: 'Clothes', common: false },
  { word: 'gingham', wiki: 'Gingham', category: 'Clothes', common: false },
  { word: 'glengarry', wiki: 'Glengarry', category: 'Clothes', common: false },
  { word: 'gorget', wiki: 'Gorget', category: 'Clothes', common: false },
  { word: 'greatcoat', wiki: 'Greatcoat', category: 'Clothes', common: false },
  { word: 'guernsey', wiki: 'Guernsey', category: 'Nature', common: false },
  { word: 'gusset', wiki: 'Gusset', category: 'Clothes', common: false },
  { word: 'habit', wiki: 'Habit', category: 'Clothes', common: false },
  { word: 'half-mast', wiki: 'Half-mast', category: 'Vehicles', common: false },
  { word: 'hatstand', wiki: 'Hatstand', category: 'Places', common: false },
  { word: 'hoodie', wiki: 'Hoodie', category: 'Clothes', common: false },
  { word: 'houppelande', wiki: 'Houppelande', category: 'Clothes', common: false },
  { word: 'ihram', wiki: 'Ihram', category: 'Clothes', article: 'an', common: false },
  { word: 'jerkin', wiki: 'Jerkin', category: 'Clothes', common: false },
  { word: 'jodhpurs', wiki: 'Jodhpurs', category: 'Clothes', common: false },
  { word: 'kirtle', wiki: 'Kirtle', category: 'Clothes', common: false },
  { word: 'krama', wiki: 'Krama', category: 'Clothes', common: false },
  { word: 'lap', wiki: 'Lap', category: 'Clothes', common: false },
  { word: 'laticlave', wiki: 'Laticlave', category: 'Clothes', common: false },
  { word: 'leotard', wiki: 'Leotard', category: 'Clothes', common: false },
  { word: 'lingerie', wiki: 'Lingerie', category: 'Clothes', common: false },
  { word: 'lumberjack', wiki: 'Lumberjack', category: 'Jobs', common: false },
  { word: 'lungi', wiki: 'Lungi', category: 'Clothes', common: false },
  { word: 'mantilla', wiki: 'Mantilla', category: 'Clothes', common: false },
  { word: 'matchcoat', wiki: 'Matchcoat', category: 'Clothes', common: false },
  { word: 'mufti', wiki: 'Mufti', category: 'Clothes', common: false },
  { word: 'neckline', wiki: 'Neckline', category: 'Clothes', common: false },
  { word: 'nightshirt', wiki: 'Nightshirt', category: 'Clothes', common: false },
  { word: 'nightwear', wiki: 'Nightwear', category: 'Clothes', common: false },
  { word: 'nubia', wiki: 'Nubia', category: 'Clothes', common: false },
  { word: 'overalls', wiki: 'Overalls', category: 'Clothes', article: 'an', common: false },
  { word: 'overcoat', wiki: 'Overcoat', category: 'Clothes', article: 'an', common: false },
  { word: 'overskirt', wiki: 'Overskirt', category: 'Clothes', article: 'an', common: false },
  { word: 'paletot', wiki: 'Paletot', category: 'Clothes', common: false },
  { word: 'paludamentum', wiki: 'Paludamentum', category: 'Clothes', common: false },
  { word: 'partlet', wiki: 'Partlet', category: 'Clothes', common: false },
  { word: 'peekaboo', wiki: 'Peekaboo', category: 'Sport', common: false },
  { word: 'peignoir', wiki: 'Peignoir', category: 'Clothes', common: false },
  { word: 'pelerine', wiki: 'Pelerine', category: 'Clothes', common: false },
  { word: 'pelisse', wiki: 'Pelisse', category: 'Clothes', common: false },
  { word: 'peplos', wiki: 'Peplos', category: 'Clothes', common: false },
  { word: 'pinafore', wiki: 'Pinafore', category: 'Clothes', common: false },
  { word: 'placket', wiki: 'Placket', category: 'Clothes', common: false },
  { word: 'polonaise', wiki: 'Polonaise', category: 'Clothes', common: false },
  { word: 'popover', wiki: 'Popover', category: 'Clothes', common: false },
  { word: 'pourpoint', wiki: 'Pourpoint', category: 'Clothes', common: false },
  { word: 'purdah', wiki: 'Purdah', category: 'Clothes', common: false },
  { word: 'puttee', wiki: 'Puttee', category: 'Clothes', common: false },
  { word: 'ready-to-wear', wiki: 'Ready-to-wear', category: 'Clothes', common: false },
  { word: 'ruana', wiki: 'Ruana', category: 'Clothes', common: false },
  { word: 'sanbenito', wiki: 'Sanbenito', category: 'Clothes', common: false },
  { word: 'sari', wiki: 'Sari', category: 'Clothes', common: false },
  { word: 'sark', wiki: 'Sark', category: 'Nature', common: false },
  { word: 'sequin', wiki: 'Sequin', category: 'Clothes', common: false },
  { word: 'serape', wiki: 'Serape', category: 'Clothes', common: false },
  { word: 'shadbelly', wiki: 'Shadbelly', category: 'Clothes', common: false },
  { word: 'shirring', wiki: 'Shirring', category: 'Clothes', common: false },
  { word: 'shrug', wiki: 'Shrug', category: 'Clothes', common: false },
  { word: 'simar', wiki: 'Simar', category: 'Clothes', common: false },
  { word: 'single-breasted', wiki: 'Single-breasted', category: 'Clothes', common: false },
  { word: 'sleeve', wiki: 'Sleeve', category: 'Clothes', common: false },
  { word: 'slinky', wiki: 'Slinky', category: 'Toys', common: false },
  { word: 'sportswear', wiki: 'Sportswear', category: 'Clothes', common: false },
  { word: 'stola', wiki: 'Stola', category: 'Clothes', common: false },
  { word: 'sulu', wiki: 'Sulu', category: 'Clothes', common: false },
  { word: 'surcoat', wiki: 'Surcoat', category: 'Clothes', common: false },
  { word: 'surtout', wiki: 'Surtout', category: 'Clothes', common: false },
  { word: 'suspenders', wiki: 'Suspenders', category: 'Clothes', common: false },
  { word: 'swaddling', wiki: 'Swaddling', category: 'Clothes', common: false },
  { word: 'tabard', wiki: 'Tabard', category: 'Clothes', common: false },
  { word: 'talar', wiki: 'Talar', category: 'Clothes', common: false },
  { word: 'tank', wiki: 'Tank', category: 'Vehicles', common: false },
  { word: 'tee', wiki: 'Tee', category: 'Sport', common: false },
  { word: 'toga', wiki: 'Toga', category: 'Clothes', common: false },
  { word: 'truss', wiki: 'Truss', category: 'Places', common: false },
  { word: 'ulster', wiki: 'Ulster', category: 'Clothes', article: 'an', common: false },
  { word: 'underpants', wiki: 'Underpants', category: 'Clothes', article: 'an', common: false },
  { word: 'underwear', wiki: 'Underwear', category: 'Clothes', article: 'an', common: false },
  { word: 'vestment', wiki: 'Vestment', category: 'Clothes', common: false },
  { word: 'waistband', wiki: 'Waistband', category: 'Clothes', common: false },
  { word: 'wear', wiki: 'Wear', category: 'Clothes', common: false },
  { word: 'windbreaker', wiki: 'Windbreaker', category: 'Weather', common: false },
  { word: 'witzchoura', wiki: 'Witzchoura', category: 'Clothes', common: false },
  { word: 'yoke', wiki: 'Yoke', category: 'Clothes', common: false },
  { word: 'zamarra', wiki: 'Zamarra', category: 'Clothes', common: false },
  { word: 'arctic', wiki: 'Arctic', category: 'Clothes', article: 'an', common: false },
  { word: 'barefoot', wiki: 'Barefoot', category: 'Clothes', common: false },
  { word: 'buskin', wiki: 'Buskin', category: 'Clothes', common: false },
  { word: 'chopine', wiki: 'Chopine', category: 'Clothes', common: false },
  { word: 'clog', wiki: 'Clog', category: 'Clothes', common: false },
  { word: 'crampon', wiki: 'Crampon', category: 'Clothes', common: false },
  { word: 'discalced', wiki: 'Discalced', category: 'Clothes', common: false },
  { word: 'elevator', wiki: 'Elevator', category: 'Clothes', article: 'an', common: false },
  { word: 'fin', wiki: 'Fin', category: 'Places', common: false },
  { word: 'floater', wiki: 'Floater', category: 'Clothes', common: false },
  { word: 'hobnail', wiki: 'Hobnail', category: 'Clothes', common: false },
  { word: 'horseshoe', wiki: 'Horseshoe', category: 'Clothes', common: false },
  { word: 'last', wiki: 'Last', category: 'Clothes', common: false },
  { word: 'mukluk', wiki: 'Mukluk', category: 'Clothes', common: false },
  { word: 'napoleon', wiki: 'Napoleon', category: 'Clothes', common: false },
  { word: 'nylon', wiki: 'Nylon', category: 'Clothes', common: false },
  { word: 'oxford', wiki: 'Oxford', category: 'Clothes', article: 'an', common: false },
  { word: 'poulaine', wiki: 'Poulaine', category: 'Clothes', common: false },
  { word: 'pump', wiki: 'Pump', category: 'Clothes', common: false },
  { word: 'saddle', wiki: 'Saddle', category: 'Places', common: false },
  { word: 'shoehorn', wiki: 'Shoehorn', category: 'Clothes', common: false },
  { word: 'snowshoe', wiki: 'Snowshoe', category: 'Clothes', common: false },
  { word: 'spur', wiki: 'Spur', category: 'Home', common: false },
  { word: 'stepper', wiki: 'Stepper', category: 'Home', common: false },
  { word: 'talaria', wiki: 'Talaria', category: 'Clothes', common: false },
  { word: 'thong', wiki: 'Thong', category: 'Clothes', common: false },
  { word: 'bashlyk', wiki: 'Bashlyk', category: 'Clothes', common: false },
  { word: 'bearskin', wiki: 'Bearskin', category: 'Clothes', common: false },
  { word: 'bicorn', wiki: 'Bicorn', category: 'Clothes', common: false },
  { word: 'bicorne', wiki: 'Bicorne', category: 'Clothes', common: false },
  { word: 'biretta', wiki: 'Biretta', category: 'Clothes', common: false },
  { word: 'blindfold', wiki: 'Blindfold', category: 'Clothes', common: false },
  { word: 'boater', wiki: 'Boater', category: 'Clothes', common: false },
  { word: 'burgonet', wiki: 'Burgonet', category: 'Clothes', common: false },
  { word: 'castoreum', wiki: 'Castoreum', category: 'Clothes', common: false },
  { word: 'caubeen', wiki: 'Caubeen', category: 'Clothes', common: false },
  { word: 'circlet', wiki: 'Circlet', category: 'Clothes', common: false },
  { word: 'coif', wiki: 'Coif', category: 'Clothes', common: false },
  { word: 'coronet', wiki: 'Coronet', category: 'Clothes', common: false },
  { word: 'diadem', wiki: 'Diadem', category: 'Clothes', common: false },
  { word: 'fedora', wiki: 'Fedora', category: 'Clothes', common: false },
  { word: 'felt', wiki: 'Felt', category: 'Clothes', common: false },
  { word: 'headgear', wiki: 'Headgear', category: 'Clothes', common: false },
  { word: 'headpiece', wiki: 'Headpiece', category: 'Clothes', common: false },
  { word: 'hennin', wiki: 'Hennin', category: 'Clothes', common: false },
  { word: 'kerchief', wiki: 'Kerchief', category: 'Clothes', common: false },
  { word: 'mitre', wiki: 'Mitre', category: 'Clothes', common: false },
  { word: 'mound', wiki: 'Mound', category: 'Clothes', common: false },
  { word: 'muffler', wiki: 'Muffler', category: 'Clothes', common: false },
  { word: 'porringer', wiki: 'Porringer', category: 'Clothes', common: false },
  { word: 'pschent', wiki: 'Pschent', category: 'Clothes', common: false },
  { word: 'pug', wiki: 'Pug', category: 'Clothes', common: false },
  { word: 'sallet', wiki: 'Sallet', category: 'Clothes', common: false },
  { word: 'shako', wiki: 'Shako', category: 'Clothes', common: false },
  { word: 'shtreimel', wiki: 'Shtreimel', category: 'Clothes', common: false },
  { word: 'tarpaulin', wiki: 'Tarpaulin', category: 'Clothes', common: false },
  { word: 'topi', wiki: 'Topi', category: 'Clothes', common: false },
  { word: 'toque', wiki: 'Toque', category: 'Clothes', common: false },
  { word: 'trilby', wiki: 'Trilby', category: 'Clothes', common: false },
  { word: 'visor', wiki: 'Visor', category: 'Clothes', common: false },
  { word: 'wig', wiki: 'Wig', category: 'Clothes', common: false },
  { word: 'wimple', wiki: 'Wimple', category: 'Clothes', common: false },
  { word: 'wreath', wiki: 'Wreath', category: 'Clothes', common: false },
  { word: 'zucchetto', wiki: 'Zucchetto', category: 'Clothes', common: false },
  { word: 'amulet', wiki: 'Amulet', category: 'Clothes', article: 'an', common: false },
  { word: 'anklet', wiki: 'Anklet', category: 'Clothes', article: 'an', common: false },
  { word: 'bangle', wiki: 'Bangle', category: 'Clothes', common: false },
  { word: 'choker', wiki: 'Choker', category: 'Clothes', common: false },
  { word: 'collet', wiki: 'Collet', category: 'Clothes', common: false },
  { word: 'fibula', wiki: 'Fibula', category: 'Body', common: false },
  { word: 'filigree', wiki: 'Filigree', category: 'Clothes', common: false },
  { word: 'marcasite', wiki: 'Marcasite', category: 'Places', common: false },
  { word: 'parure', wiki: 'Parure', category: 'Clothes', common: false },
  { word: 'pendant', wiki: 'Pendant', category: 'Clothes', common: false },
  { word: 'rhinestone', wiki: 'Rhinestone', category: 'Clothes', common: false },
  { word: 'rosedrop', wiki: 'Rosedrop', category: 'Clothes', common: false },
  { word: 'solitaire', wiki: 'Solitaire', category: 'Clothes', common: false },
  { word: 'torque', wiki: 'Torque', category: 'Clothes', common: false },
  { word: 'baize', wiki: 'Baize', category: 'Clothes', common: false },
  { word: 'barathea', wiki: 'Barathea', category: 'Clothes', common: false },
  { word: 'bengaline', wiki: 'Bengaline', category: 'Clothes', common: false },
  { word: 'bobbinet', wiki: 'Bobbinet', category: 'Clothes', common: false },
  { word: 'bombazine', wiki: 'Bombazine', category: 'Clothes', common: false },
  { word: 'brilliantine', wiki: 'Brilliantine', category: 'Clothes', common: false },
  { word: 'broadcloth', wiki: 'Broadcloth', category: 'Clothes', common: false },
  { word: 'brocade', wiki: 'Brocade', category: 'Clothes', common: false },
  { word: 'buckram', wiki: 'Buckram', category: 'Clothes', common: false },
  { word: 'byssus', wiki: 'Byssus', category: 'Clothes', common: false },
  { word: 'calico', wiki: 'Calico', category: 'Clothes', common: false },
  { word: 'cambric', wiki: 'Cambric', category: 'Clothes', common: false },
  { word: 'ambry', wiki: 'Ambry', category: 'Home', article: 'an', common: false },
  { word: 'antimacassar', wiki: 'Antimacassar', category: 'Home', article: 'an', common: false },
  { word: 'bier', wiki: 'Bier', category: 'Home', common: false },
  { word: 'closet', wiki: 'Closet', category: 'Home', common: false },
  { word: 'cornice', wiki: 'Cornice', category: 'Home', common: false },
  { word: 'dais', wiki: 'Dais', category: 'Home', common: false },
  { word: 'divan', wiki: 'Divan', category: 'Home', common: false },
  { word: 'empire', wiki: 'Empire', category: 'Home', article: 'an', common: false },
  { word: 'encoignure', wiki: 'Encoignure', category: 'Home', article: 'an', common: false },
  { word: 'footstool', wiki: 'Footstool', category: 'Home', common: false },
  { word: 'kneeler', wiki: 'Kneeler', category: 'Home', common: false },
  { word: 'lowboy', wiki: 'Lowboy', category: 'Home', common: false },
  { word: 'oilcloth', wiki: 'Oilcloth', category: 'Home', article: 'an', common: false },
  { word: 'playpen', wiki: 'Playpen', category: 'Home', common: false },
  { word: 'sideboard', wiki: 'Sideboard', category: 'Home', common: false },
  { word: 'squab', wiki: 'Squab', category: 'Food', common: false },
  { word: 'stretcher', wiki: 'Stretcher', category: 'Home', common: false },
  { word: 'taboret', wiki: 'Taboret', category: 'Home', common: false },
  { word: 'triclinium', wiki: 'Triclinium', category: 'Places', common: false },
  { word: 'vanity', wiki: 'Vanity', category: 'Home', common: false },
  { word: 'washstand', wiki: 'Washstand', category: 'Home', common: false },
  { word: 'workbench', wiki: 'Workbench', category: 'Home', common: false },
  { word: 'adze', wiki: 'Adze', category: 'Home', article: 'an', common: false },
  { word: 'anvil', wiki: 'Anvil', category: 'Home', article: 'an', common: false },
  { word: 'aspergillum', wiki: 'Aspergillum', category: 'Home', article: 'an', common: false },
  { word: 'athanor', wiki: 'Athanor', category: 'Home', article: 'an', common: false },
  { word: 'bellows', wiki: 'Bellows', category: 'Home', common: false },
  { word: 'besom', wiki: 'Besom', category: 'Home', common: false },
  { word: 'billhook', wiki: 'Billhook', category: 'Home', common: false },
  { word: 'blowtorch', wiki: 'Blowtorch', category: 'Home', common: false },
  { word: 'burnisher', wiki: 'Burnisher', category: 'Home', common: false },
  { word: 'cleaver', wiki: 'Cleaver', category: 'Home', common: false },
  { word: 'clipper', wiki: 'Clipper', category: 'Vehicles', common: false },
  { word: 'come-along', wiki: 'Come-along', category: 'Home', common: false },
  { word: 'counterbore', wiki: 'Counterbore', category: 'Home', common: false },
  { word: 'crutch', wiki: 'Crutch', category: 'Home', common: false },
  { word: 'distaff', wiki: 'Distaff', category: 'Home', common: false },
  { word: 'enoch', wiki: 'Enoch', category: 'Home', article: 'an', common: false },
  { word: 'ferrule', wiki: 'Ferrule', category: 'Home', common: false },
  { word: 'footman', wiki: 'Footman', category: 'Jobs', common: false },
  { word: 'forceps', wiki: 'Forceps', category: 'Home', common: false },
  { word: 'froe', wiki: 'Froe', category: 'Home', common: false },
  { word: 'gambrel', wiki: 'Gambrel', category: 'Home', common: false },
  { word: 'gill', wiki: 'Gill', category: 'Body', common: false },
  { word: 'grindstone', wiki: 'Grindstone', category: 'Home', common: false },
  { word: 'hickey', wiki: 'Hickey', category: 'Home', common: false },
  { word: 'jackhammer', wiki: 'Jackhammer', category: 'Home', common: false },
  { word: 'jointer', wiki: 'Jointer', category: 'Home', common: false },
  { word: 'lance', wiki: 'Lance', category: 'Home', common: false },
  { word: 'lighter', wiki: 'Lighter', category: 'Home', common: false },
  { word: 'lucet', wiki: 'Lucet', category: 'Home', common: false },
  { word: 'mandrel', wiki: 'Mandrel', category: 'Home', common: false },
  { word: 'mattock', wiki: 'Mattock', category: 'Home', common: false },
  { word: 'millstone', wiki: 'Millstone', category: 'Home', common: false },
  { word: 'nutcracker', wiki: 'Nutcracker', category: 'Home', common: false },
  { word: 'peeler', wiki: 'Peeler', category: 'Home', common: false },
  { word: 'penknife', wiki: 'Penknife', category: 'Home', common: false },
  { word: 'pitchfork', wiki: 'Pitchfork', category: 'Home', common: false },
  { word: 'plough', wiki: 'Plough', category: 'Home', common: false },
  { word: 'pocketknife', wiki: 'Pocketknife', category: 'Home', common: false },
  { word: 'poker', wiki: 'Poker', category: 'Home', common: false },
  { word: 'priest', wiki: 'Priest', category: 'Home', common: false },
  { word: 'rasp', wiki: 'Rasp', category: 'Home', common: false },
  { word: 'sander', wiki: 'Sander', category: 'Home', common: false },
  { word: 'scrapple', wiki: 'Scrapple', category: 'Home', common: false },
  { word: 'screed', wiki: 'Screed', category: 'Places', common: false },
  { word: 'scythe', wiki: 'Scythe', category: 'Home', common: false },
  { word: 'shadoof', wiki: 'Shadoof', category: 'Home', common: false },
  { word: 'sickle', wiki: 'Sickle', category: 'Home', common: false },
  { word: 'spokeshave', wiki: 'Spokeshave', category: 'Home', common: false },
  { word: 'squeegee', wiki: 'Squeegee', category: 'Home', common: false },
  { word: 'temse', wiki: 'Temse', category: 'Home', common: false },
  { word: 'trivet', wiki: 'Trivet', category: 'Food', common: false },
  { word: 't-square', wiki: 'T-square', category: 'Home', common: false },
  { word: 'ultramicroscope', wiki: 'Ultramicroscope', category: 'Home', article: 'an', common: false },
  { word: 'vice', wiki: 'Vice', category: 'Home', common: false },
  { word: 'vise', wiki: 'Vise', category: 'Home', common: false },
  { word: 'winch', wiki: 'Winch', category: 'Home', common: false },
  { word: 'cheesecloth', wiki: 'Cheesecloth', category: 'Home', common: false },
  { word: 'china', wiki: 'China', category: 'Home', common: false },
  { word: 'kitchenware', wiki: 'Kitchenware', category: 'Food', common: false },
  { word: 'tableware', wiki: 'Tableware', category: 'Food', common: false },
  { word: 'tureen', wiki: 'Tureen', category: 'Food', common: false },
  { word: 'albarello', wiki: 'Albarello', category: 'Home', article: 'an', common: false },
  { word: 'ampoule', wiki: 'Ampoule', category: 'Home', article: 'an', common: false },
  { word: 'ampulla', wiki: 'Ampulla', category: 'Home', article: 'an', common: false },
  { word: 'barrel', wiki: 'Barrel', category: 'Home', common: false },
  { word: 'bindle', wiki: 'Bindle', category: 'Home', common: false },
  { word: 'caddie', wiki: 'Caddie', category: 'Jobs', common: false },
  { word: 'carboy', wiki: 'Carboy', category: 'Home', common: false },
  { word: 'carton', wiki: 'Carton', category: 'Home', common: false },
  { word: 'coffin', wiki: 'Coffin', category: 'Home', common: false },
  { word: 'container', wiki: 'Container', category: 'Home', common: false },
  { word: 'corf', wiki: 'Corf', category: 'Home', common: false },
  { word: 'cresset', wiki: 'Cresset', category: 'Home', common: false },
  { word: 'crucible', wiki: 'Crucible', category: 'Home', common: false },
  { word: 'cruet', wiki: 'Cruet', category: 'Home', common: false },
  { word: 'cuvette', wiki: 'Cuvette', category: 'Home', common: false },
  { word: 'gallipot', wiki: 'Gallipot', category: 'Home', common: false },
  { word: 'hamper', wiki: 'Hamper', category: 'Home', common: false },
  { word: 'hanaper', wiki: 'Hanaper', category: 'Home', common: false },
  { word: 'jordan', wiki: 'Jordan', category: 'Home', common: false },
  { word: 'keg', wiki: 'Keg', category: 'Home', common: false },
  { word: 'larnax', wiki: 'Larnax', category: 'Home', common: false },
  { word: 'matchbox', wiki: 'Matchbox', category: 'Home', common: false },
  { word: 'monstrance', wiki: 'Monstrance', category: 'Home', common: false },
  { word: 'ossuary', wiki: 'Ossuary', category: 'Home', article: 'an', common: false },
  { word: 'pannier', wiki: 'Pannier', category: 'Home', common: false },
  { word: 'pelike', wiki: 'Pelike', category: 'Shapes', common: false },
  { word: 'psykter', wiki: 'Psykter', category: 'Home', common: false },
  { word: 'punnet', wiki: 'Punnet', category: 'Home', common: false },
  { word: 'pyxis', wiki: 'Pyxis', category: 'Home', common: false },
  { word: 'quiver', wiki: 'Quiver', category: 'Home', common: false },
  { word: 'reliquary', wiki: 'Reliquary', category: 'Home', common: false },
  { word: 'rhyton', wiki: 'Rhyton', category: 'Home', common: false },
  { word: 'rummer', wiki: 'Rummer', category: 'Home', common: false },
  { word: 'safe', wiki: 'Safe', category: 'Home', common: false },
  { word: 'soapbox', wiki: 'Soapbox', category: 'Home', common: false },
  { word: 'spittoon', wiki: 'Spittoon', category: 'Home', common: false },
  { word: 'stamnos', wiki: 'Stamnos', category: 'Home', common: false },
  { word: 'suitcase', wiki: 'Suitcase', category: 'Home', common: false },
  { word: 'unguentarium', wiki: 'Unguentarium', category: 'Home', article: 'an', common: false },
  { word: 'urn', wiki: 'Urn', category: 'Home', article: 'an', common: false },
  { word: 'vial', wiki: 'Vial', category: 'Home', common: false },
  { word: 'wallet', wiki: 'Wallet', category: 'Home', common: false },
  { word: 'waterskin', wiki: 'Waterskin', category: 'Home', common: false },
  { word: 'zarf', wiki: 'Zarf', category: 'Home', common: false },
  { word: 'tablespoon', wiki: 'Tablespoon', category: 'Home', common: false },
  { word: 'teaspoon', wiki: 'Teaspoon', category: 'Home', common: false },
  { word: 'ulu', wiki: 'Ulu', category: 'Home', article: 'an', common: false },
  { word: 'bedding', wiki: 'Bedding', category: 'Home', common: false },
  { word: 'bolster', wiki: 'Bolster', category: 'Home', common: false },
  { word: 'comforter', wiki: 'Comforter', category: 'Home', common: false },
  { word: 'king', wiki: 'King', category: 'Home', common: false },
  { word: 'litter', wiki: 'Litter', category: 'Home', common: false },
  { word: 'stylus', wiki: 'Stylus', category: 'School', common: false },
  { word: 'abecedarium', wiki: 'Abecedarium', category: 'School', article: 'an', common: false },
  { word: 'avesta', wiki: 'Avesta', category: 'School', article: 'an', common: false },
  { word: 'bible', wiki: 'Bible', category: 'School', common: false },
  { word: 'bookselling', wiki: 'Bookselling', category: 'School', common: false },
  { word: 'breviary', wiki: 'Breviary', category: 'School', common: false },
  { word: 'catechism', wiki: 'Catechism', category: 'School', common: false },
  { word: 'chapbook', wiki: 'Chapbook', category: 'School', common: false },
  { word: 'chronicle', wiki: 'Chronicle', category: 'School', common: false },
  { word: 'codex', wiki: 'Codex', category: 'School', common: false },
  { word: 'cookbook', wiki: 'Cookbook', category: 'School', common: false },
  { word: 'doorstop', wiki: 'Doorstop', category: 'School', common: false },
  { word: 'folio', wiki: 'Folio', category: 'School', common: false },
  { word: 'hansard', wiki: 'Hansard', category: 'School', common: false },
  { word: 'hexapla', wiki: 'Hexapla', category: 'School', common: false },
  { word: 'hornbook', wiki: 'Hornbook', category: 'School', common: false },
  { word: 'logbook', wiki: 'Logbook', category: 'School', common: false },
  { word: 'memoir', wiki: 'Memoir', category: 'School', common: false },
  { word: 'menologium', wiki: 'Menologium', category: 'School', common: false },
  { word: 'missal', wiki: 'Missal', category: 'School', common: false },
  { word: 'monograph', wiki: 'Monograph', category: 'School', common: false },
  { word: 'paperback', wiki: 'Paperback', category: 'School', common: false },
  { word: 'papyrology', wiki: 'Papyrology', category: 'School', common: false },
  { word: 'pharmacopoeia', wiki: 'Pharmacopoeia', category: 'School', common: false },
  { word: 'roadbook', wiki: 'Roadbook', category: 'School', common: false },
  { word: 'septuagint', wiki: 'Septuagint', category: 'School', common: false },
  { word: 'sketchbook', wiki: 'Sketchbook', category: 'School', common: false },
  { word: 'talmud', wiki: 'Talmud', category: 'School', common: false },
  { word: 'vulgate', wiki: 'Vulgate', category: 'School', common: false },
  { word: 'yearbook', wiki: 'Yearbook', category: 'School', common: false },
  { word: 'cup-and-ball', wiki: 'Cup-and-ball', category: 'Toys', common: false },
  { word: 'phenakistoscope', wiki: 'Phenakistoscope', category: 'Toys', common: false },
  { word: 'spirograph', wiki: 'Spirograph', category: 'Shapes', common: false },
  { word: 'teetotum', wiki: 'Teetotum', category: 'Toys', common: false },
  { word: 'thaumatrope', wiki: 'Thaumatrope', category: 'Toys', common: false },
  { word: 'zoetrope', wiki: 'Zoetrope', category: 'Toys', common: false },
  { word: 'checkerboard', wiki: 'Checkerboard', category: 'Toys', common: false },
  { word: 'coronation', wiki: 'Coronation', category: 'Toys', common: false },
  { word: 'crokinole', wiki: 'Crokinole', category: 'Toys', common: false },
  { word: 'energy', wiki: 'Energy', category: 'Toys', article: 'an', common: false },
  { word: 'halma', wiki: 'Halma', category: 'Toys', common: false },
  { word: 'home', wiki: 'Home', category: 'Toys', common: false },
  { word: 'ludo', wiki: 'Ludo', category: 'Toys', common: false },
  { word: 'othello', wiki: 'Othello', category: 'Toys', article: 'an', common: false },
  { word: 'ouija', wiki: 'Ouija', category: 'Toys', article: 'an', common: false },
  { word: 'shogi', wiki: 'Shogi', category: 'Toys', common: false },
  { word: 'bagnio', wiki: 'Bagnio', category: 'Places', common: false },
  { word: 'barbican', wiki: 'Barbican', category: 'Places', common: false },
  { word: 'bastide', wiki: 'Bastide', category: 'Places', common: false },
  { word: 'bastille', wiki: 'Bastille', category: 'Places', common: false },
  { word: 'blockhouse', wiki: 'Blockhouse', category: 'Places', common: false },
  { word: 'bothy', wiki: 'Bothy', category: 'Places', common: false },
  { word: 'brewery', wiki: 'Brewery', category: 'Places', common: false },
  { word: 'brothel', wiki: 'Brothel', category: 'Places', common: false },
  { word: 'building', wiki: 'Building', category: 'Places', common: false },
  { word: 'caravanserai', wiki: 'Caravanserai', category: 'Places', common: false },
  { word: 'chalet', wiki: 'Chalet', category: 'Places', common: false },
  { word: 'citadel', wiki: 'Citadel', category: 'Places', common: false },
  { word: 'colosseum', wiki: 'Colosseum', category: 'Places', common: false },
  { word: 'commons', wiki: 'Commons', category: 'Places', common: false },
  { word: 'convent', wiki: 'Convent', category: 'Places', common: false },
  { word: 'counter-castle', wiki: 'Counter-castle', category: 'Places', common: false },
  { word: 'courthouse', wiki: 'Courthouse', category: 'Places', common: false },
  { word: 'farmstead', wiki: 'Farmstead', category: 'Places', common: false },
  { word: 'folly', wiki: 'Folly', category: 'Places', common: false },
  { word: 'gang', wiki: 'Gang', category: 'Places', common: false },
  { word: 'granary', wiki: 'Granary', category: 'Places', common: false },
  { word: 'guardhouse', wiki: 'Guardhouse', category: 'Places', common: false },
  { word: 'house-commune', wiki: 'House-commune', category: 'Places', common: false },
  { word: 'kremlin', wiki: 'Kremlin', category: 'Places', common: false },
  { word: 'lazaretto', wiki: 'Lazaretto', category: 'Places', common: false },
  { word: 'memorial', wiki: 'Memorial', category: 'Places', common: false },
  { word: 'morgue', wiki: 'Morgue', category: 'Places', common: false },
  { word: 'outbuilding', wiki: 'Outbuilding', category: 'Places', article: 'an', common: false },
  { word: 'outhouse', wiki: 'Outhouse', category: 'Places', article: 'an', common: false },
  { word: 'pagoda', wiki: 'Pagoda', category: 'Places', common: false },
  { word: 'priory', wiki: 'Priory', category: 'Places', common: false },
  { word: 'refinery', wiki: 'Refinery', category: 'Places', common: false },
  { word: 'revetment', wiki: 'Revetment', category: 'Places', common: false },
  { word: 'sanatorium', wiki: 'Sanatorium', category: 'Places', common: false },
  { word: 'senate', wiki: 'Senate', category: 'Places', common: false },
  { word: 'seraglio', wiki: 'Seraglio', category: 'Places', common: false },
  { word: 'shack', wiki: 'Shack', category: 'Places', common: false },
  { word: 'siege', wiki: 'Siege', category: 'Places', common: false },
  { word: 'silo', wiki: 'Silo', category: 'Places', common: false },
  { word: 'slaughterhouse', wiki: 'Slaughterhouse', category: 'Places', common: false },
  { word: 'synagogue', wiki: 'Synagogue', category: 'Places', common: false },
  { word: 'watchtower', wiki: 'Watchtower', category: 'Places', common: false },
  { word: 'wigwam', wiki: 'Wigwam', category: 'Places', common: false },
  { word: 'winery', wiki: 'Winery', category: 'Places', common: false },
  { word: 'yurt', wiki: 'Yurt', category: 'Places', common: false },
  { word: 'attic', wiki: 'Attic', category: 'Places', article: 'an', common: false },
  { word: 'auditorium', wiki: 'Auditorium', category: 'Places', article: 'an', common: false },
  { word: 'ballroom', wiki: 'Ballroom', category: 'Places', common: false },
  { word: 'bathroom', wiki: 'Bathroom', category: 'Places', common: false },
  { word: 'bedroom', wiki: 'Bedroom', category: 'Places', common: false },
  { word: 'boudoir', wiki: 'Boudoir', category: 'Places', common: false },
  { word: 'cafeteria', wiki: 'Cafeteria', category: 'Food', common: false },
  { word: 'calefactory', wiki: 'Calefactory', category: 'Places', common: false },
  { word: 'cockloft', wiki: 'Cockloft', category: 'Places', common: false },
  { word: 'confessional', wiki: 'Confessional', category: 'Places', common: false },
  { word: 'courtroom', wiki: 'Courtroom', category: 'Places', common: false },
  { word: 'cubicle', wiki: 'Cubicle', category: 'Home', common: false },
  { word: 'cubiculum', wiki: 'Cubiculum', category: 'Places', common: false },
  { word: 'darkroom', wiki: 'Darkroom', category: 'Places', common: false },
  { word: 'galley', wiki: 'Galley', category: 'Vehicles', common: false },
  { word: 'garderobe', wiki: 'Garderobe', category: 'Places', common: false },
  { word: 'garret', wiki: 'Garret', category: 'Places', common: false },
  { word: 'laconicum', wiki: 'Laconicum', category: 'Places', common: false },
  { word: 'larder', wiki: 'Larder', category: 'Places', common: false },
  { word: 'latrine', wiki: 'Latrine', category: 'Places', common: false },
  { word: 'lavabo', wiki: 'Lavabo', category: 'Places', common: false },
  { word: 'loft', wiki: 'Loft', category: 'Places', common: false },
  { word: 'mausoleum', wiki: 'Mausoleum', category: 'Places', common: false },
  { word: 'megaron', wiki: 'Megaron', category: 'Places', common: false },
  { word: 'opisthodomos', wiki: 'Opisthodomos', category: 'Places', article: 'an', common: false },
  { word: 'panopticon', wiki: 'Panopticon', category: 'Places', common: false },
  { word: 'refectory', wiki: 'Refectory', category: 'Places', common: false },
  { word: 'room', wiki: 'Room', category: 'Places', common: false },
  { word: 'sacristy', wiki: 'Sacristy', category: 'Places', common: false },
  { word: 'scullery', wiki: 'Scullery', category: 'Places', common: false },
  { word: 'showroom', wiki: 'Showroom', category: 'Places', common: false },
  { word: 'sunroom', wiki: 'Sunroom', category: 'Places', common: false },
  { word: 'teahouse', wiki: 'Teahouse', category: 'Places', common: false },
  { word: 'tepidarium', wiki: 'Tepidarium', category: 'Places', common: false },
  { word: 'undercroft', wiki: 'Undercroft', category: 'Places', article: 'an', common: false },
  { word: 'vestry', wiki: 'Vestry', category: 'Places', common: false },
  { word: 'xenodochium', wiki: 'Xenodochium', category: 'Places', common: false },
  { word: 'delicatessen', wiki: 'Delicatessen', category: 'Places', common: false },
  { word: 'vintry', wiki: 'Vintry', category: 'Places', common: false },
  { word: 'axle', wiki: 'Axle', category: 'Vehicles', article: 'an', common: false },
  { word: 'barouche', wiki: 'Barouche', category: 'Vehicles', common: false },
  { word: 'bloodmobile', wiki: 'Bloodmobile', category: 'Vehicles', common: false },
  { word: 'bookmobile', wiki: 'Bookmobile', category: 'Vehicles', common: false },
  { word: 'cycler', wiki: 'Cycler', category: 'Vehicles', common: false },
  { word: 'dandy', wiki: 'Dandy', category: 'Vehicles', common: false },
  { word: 'dicycle', wiki: 'Dicycle', category: 'Vehicles', common: false },
  { word: 'e-scooter', wiki: 'E-scooter', category: 'Vehicles', article: 'an', common: false },
  { word: 'gharry', wiki: 'Gharry', category: 'Vehicles', common: false },
  { word: 'greyhound', wiki: 'Greyhound', category: 'Vehicles', common: false },
  { word: 'handcar', wiki: 'Handcar', category: 'Vehicles', common: false },
  { word: 'hearse', wiki: 'Hearse', category: 'Vehicles', common: false },
  { word: 'kago', wiki: 'Kago', category: 'Home', common: false },
  { word: 'kibitka', wiki: 'Kibitka', category: 'Vehicles', common: false },
  { word: 'pantechnicon', wiki: 'Pantechnicon', category: 'Vehicles', common: false },
  { word: 'quadriga', wiki: 'Quadriga', category: 'Vehicles', common: false },
  { word: 'sampan', wiki: 'Sampan', category: 'Vehicles', common: false },
  { word: 'scania', wiki: 'Scania', category: 'Vehicles', common: false },
  { word: 'schooner', wiki: 'Schooner', category: 'Vehicles', common: false },
  { word: 'sulky', wiki: 'Sulky', category: 'Vehicles', common: false },
  { word: 'three-wheeler', wiki: 'Three-wheeler', category: 'Vehicles', common: false },
  { word: 'toboggan', wiki: 'Toboggan', category: 'Vehicles', common: false },
  { word: 'travois', wiki: 'Travois', category: 'Places', common: false },
  { word: 'vehicle', wiki: 'Vehicle', category: 'Vehicles', common: false },
  { word: 'wagonette', wiki: 'Wagonette', category: 'Vehicles', common: false },
  { word: 'aerobus', wiki: 'Aerobus', category: 'Vehicles', article: 'an', common: false },
  { word: 'aircraft', wiki: 'Aircraft', category: 'Vehicles', article: 'an', common: false },
  { word: 'aircrew', wiki: 'Aircrew', category: 'Vehicles', article: 'an', common: false },
  { word: 'airliner', wiki: 'Airliner', category: 'Vehicles', article: 'an', common: false },
  { word: 'blimp', wiki: 'Blimp', category: 'Vehicles', common: false },
  { word: 'fuselage', wiki: 'Fuselage', category: 'Vehicles', common: false },
  { word: 'gnat', wiki: 'Gnat', category: 'Vehicles', common: false },
  { word: 'heckler', wiki: 'Heckler', category: 'Vehicles', common: false },
  { word: 'lysander', wiki: 'Lysander', category: 'Vehicles', common: false },
  { word: 'manchester', wiki: 'Manchester', category: 'Vehicles', common: false },
  { word: 'monoplane', wiki: 'Monoplane', category: 'Vehicles', common: false },
  { word: 'seaplane', wiki: 'Seaplane', category: 'Vehicles', common: false },
  { word: 'triplane', wiki: 'Triplane', category: 'Vehicles', common: false },
  { word: 'zeppelin', wiki: 'Zeppelin', category: 'Vehicles', common: false },
  { word: 'bateau', wiki: 'Bateau', category: 'Vehicles', common: false },
  { word: 'bawley', wiki: 'Bawley', category: 'Vehicles', common: false },
  { word: 'bilander', wiki: 'Bilander', category: 'Vehicles', common: false },
  { word: 'bireme', wiki: 'Bireme', category: 'Vehicles', common: false },
  { word: 'birlinn', wiki: 'Birlinn', category: 'Vehicles', common: false },
  { word: 'brig', wiki: 'Brig', category: 'Vehicles', common: false },
  { word: 'brigantine', wiki: 'Brigantine', category: 'Vehicles', common: false },
  { word: 'budgerow', wiki: 'Budgerow', category: 'Vehicles', common: false },
  { word: 'bumboat', wiki: 'Bumboat', category: 'Vehicles', common: false },
  { word: 'caique', wiki: 'Caique', category: 'Animals', common: false },
  { word: 'caper', wiki: 'Caper', category: 'Nature', common: false },
  { word: 'caravel', wiki: 'Caravel', category: 'Vehicles', common: false },
  { word: 'carrack', wiki: 'Carrack', category: 'Vehicles', common: false },
  { word: 'cataphract', wiki: 'Cataphract', category: 'Vehicles', common: false },
  { word: 'catboat', wiki: 'Catboat', category: 'Vehicles', common: false },
  { word: 'coble', wiki: 'Coble', category: 'Vehicles', common: false },
  { word: 'coracle', wiki: 'Coracle', category: 'Vehicles', common: false },
  { word: 'dhow', wiki: 'Dhow', category: 'Vehicles', common: false },
  { word: 'e-boat', wiki: 'E-boat', category: 'Vehicles', article: 'an', common: false },
  { word: 'felucca', wiki: 'Felucca', category: 'Vehicles', common: false },
  { word: 'fireboat', wiki: 'Fireboat', category: 'Vehicles', common: false },
  { word: 'flagship', wiki: 'Flagship', category: 'Vehicles', common: false },
  { word: 'flatboat', wiki: 'Flatboat', category: 'Vehicles', common: false },
  { word: 'galleass', wiki: 'Galleass', category: 'Vehicles', common: false },
  { word: 'galleon', wiki: 'Galleon', category: 'Vehicles', common: false },
  { word: 'houseboat', wiki: 'Houseboat', category: 'Vehicles', common: false },
  { word: 'iceboat', wiki: 'Iceboat', category: 'Vehicles', article: 'an', common: false },
  { word: 'icebreaker', wiki: 'Icebreaker', category: 'Vehicles', article: 'an', common: false },
  { word: 'keel', wiki: 'Keel', category: 'Vehicles', common: false },
  { word: 'keelboat', wiki: 'Keelboat', category: 'Vehicles', common: false },
  { word: 'lakatoi', wiki: 'Lakatoi', category: 'Vehicles', common: false },
  { word: 'lugger', wiki: 'Lugger', category: 'Vehicles', common: false },
  { word: 'mayflower', wiki: 'Mayflower', category: 'Vehicles', common: false },
  { word: 'moses', wiki: 'Moses', category: 'Vehicles', common: false },
  { word: 'patamar', wiki: 'Patamar', category: 'Vehicles', common: false },
  { word: 'penteconter', wiki: 'Penteconter', category: 'Vehicles', common: false },
  { word: 'proa', wiki: 'Proa', category: 'Vehicles', common: false },
  { word: 'pulwar', wiki: 'Pulwar', category: 'Vehicles', common: false },
  { word: 'scow', wiki: 'Scow', category: 'Vehicles', common: false },
  { word: 'shallop', wiki: 'Shallop', category: 'Vehicles', common: false },
  { word: 'shikara', wiki: 'Shikara', category: 'Vehicles', common: false },
  { word: 'showboat', wiki: 'Showboat', category: 'Vehicles', common: false },
  { word: 'sloop', wiki: 'Sloop', category: 'Vehicles', common: false },
  { word: 'speronara', wiki: 'Speronara', category: 'Vehicles', common: false },
  { word: 'steamship', wiki: 'Steamship', category: 'Vehicles', common: false },
  { word: 'superyacht', wiki: 'Superyacht', category: 'Vehicles', common: false },
  { word: 'tartan', wiki: 'Tartan', category: 'Vehicles', common: false },
  { word: 'titanic', wiki: 'Titanic', category: 'Vehicles', common: false },
  { word: 'tongkang', wiki: 'Tongkang', category: 'Vehicles', common: false },
  { word: 'trireme', wiki: 'Trireme', category: 'Vehicles', common: false },
  { word: 'troopship', wiki: 'Troopship', category: 'Vehicles', common: false },
  { word: 'well-boat', wiki: 'Well-boat', category: 'Vehicles', common: false },
  { word: 'whaleboat', wiki: 'Whaleboat', category: 'Vehicles', common: false },
  { word: 'whaler', wiki: 'Whaler', category: 'Vehicles', common: false },
  { word: 'wherry', wiki: 'Wherry', category: 'Vehicles', common: false },
  { word: 'xebec', wiki: 'Xebec', category: 'Vehicles', common: false },
  { word: 'yawl', wiki: 'Yawl', category: 'Vehicles', common: false },
  { word: 'zabra', wiki: 'Zabra', category: 'Vehicles', common: false },
  { word: 'clio', wiki: 'Clio', category: 'Vehicles', common: false },
  { word: 'corvette', wiki: 'Corvette', category: 'Vehicles', common: false },
  { word: 'junker', wiki: 'Junker', category: 'Vehicles', common: false },
  { word: 'mazda', wiki: 'Mazda', category: 'Vehicles', common: false },
  { word: 'mustang', wiki: 'Mustang', category: 'Vehicles', common: false },
  { word: 'plymouth', wiki: 'Plymouth', category: 'Vehicles', common: false },
  { word: 'seat', wiki: 'Seat', category: 'Vehicles', common: false },
  { word: 't-bucket', wiki: 'T-bucket', category: 'Vehicles', common: false },
  { word: 'vauxhall', wiki: 'Vauxhall', category: 'Vehicles', common: false },
  { word: 'arboretum', wiki: 'Arboretum', category: 'Nature', article: 'an', common: false },
  { word: 'bonsai', wiki: 'Bonsai', category: 'Nature', common: false },
  { word: 'deciduous', wiki: 'Deciduous', category: 'Nature', common: false },
  { word: 'elm', wiki: 'Elm', category: 'Nature', article: 'an', common: false },
  { word: 'eucalyptus', wiki: 'Eucalyptus', category: 'Nature', article: 'an', common: false },
  { word: 'evergreen', wiki: 'Evergreen', category: 'Nature', article: 'an', common: false },
  { word: 'fothergilla', wiki: 'Fothergilla', category: 'Nature', common: false },
  { word: 'geonoma', wiki: 'Geonoma', category: 'Nature', common: false },
  { word: 'greave', wiki: 'Greave', category: 'Nature', common: false },
  { word: 'holly', wiki: 'Holly', category: 'Nature', common: false },
  { word: 'longan', wiki: 'Longan', category: 'Nature', common: false },
  { word: 'measles', wiki: 'Measles', category: 'Nature', common: false },
  { word: 'monolith', wiki: 'Monolith', category: 'Nature', common: false },
  { word: 'sigillaria', wiki: 'Sigillaria', category: 'Nature', common: false },
  { word: 'allamanda', wiki: 'Allamanda', category: 'Nature', article: 'an', common: false },
  { word: 'alstroemeria', wiki: 'Alstroemeria', category: 'Nature', article: 'an', common: false },
  { word: 'amaryllis', wiki: 'Amaryllis', category: 'Nature', article: 'an', common: false },
  { word: 'begonia', wiki: 'Begonia', category: 'Nature', common: false },
  { word: 'bitterroot', wiki: 'Bitterroot', category: 'Nature', common: false },
  { word: 'bougainvillea', wiki: 'Bougainvillea', category: 'Nature', common: false },
  { word: 'calla', wiki: 'Calla', category: 'Nature', common: false },
  { word: 'camellia', wiki: 'Camellia', category: 'Nature', common: false },
  { word: 'chrysanthemum', wiki: 'Chrysanthemum', category: 'Nature', common: false },
  { word: 'clematis', wiki: 'Clematis', category: 'Nature', common: false },
  { word: 'coreopsis', wiki: 'Coreopsis', category: 'Nature', common: false },
  { word: 'cyclamen', wiki: 'Cyclamen', category: 'Nature', common: false },
  { word: 'delphinium', wiki: 'Delphinium', category: 'Nature', common: false },
  { word: 'floristry', wiki: 'Floristry', category: 'Nature', common: false },
  { word: 'freesia', wiki: 'Freesia', category: 'Nature', common: false },
  { word: 'gardenia', wiki: 'Gardenia', category: 'Nature', common: false },
  { word: 'geranium', wiki: 'Geranium', category: 'Nature', common: false },
  { word: 'gerbera', wiki: 'Gerbera', category: 'Nature', common: false },
  { word: 'gladiolus', wiki: 'Gladiolus', category: 'Nature', common: false },
  { word: 'goldenrod', wiki: 'Goldenrod', category: 'Nature', common: false },
  { word: 'hellebore', wiki: 'Hellebore', category: 'Nature', common: false },
  { word: 'hibiscus', wiki: 'Hibiscus', category: 'Nature', common: false },
  { word: 'hyacinth', wiki: 'Hyacinth', category: 'Nature', common: false },
  { word: 'hydrangea', wiki: 'Hydrangea', category: 'Nature', common: false },
  { word: 'jasmine', wiki: 'Jasmine', category: 'Nature', common: false },
  { word: 'masdevallia', wiki: 'Masdevallia', category: 'Nature', common: false },
  { word: 'myosotis', wiki: 'Myosotis', category: 'Nature', common: false },
  { word: 'nigella', wiki: 'Nigella', category: 'Nature', common: false },
  { word: 'opuntia', wiki: 'Opuntia', category: 'Nature', article: 'an', common: false },
  { word: 'osmanthus', wiki: 'Osmanthus', category: 'Nature', article: 'an', common: false },
  { word: 'pansy', wiki: 'Pansy', category: 'Nature', common: false },
  { word: 'peony', wiki: 'Peony', category: 'Nature', common: false },
  { word: 'petunia', wiki: 'Petunia', category: 'Nature', common: false },
  { word: 'poinsettia', wiki: 'Poinsettia', category: 'Nature', common: false },
  { word: 'portulaca', wiki: 'Portulaca', category: 'Nature', common: false },
  { word: 'ranunculus', wiki: 'Ranunculus', category: 'Nature', common: false },
  { word: 'rhododendron', wiki: 'Rhododendron', category: 'Nature', common: false },
  { word: 'soldanella', wiki: 'Soldanella', category: 'Nature', common: false },
  { word: 'strelitzia', wiki: 'Strelitzia', category: 'Nature', common: false },
  { word: 'syringa', wiki: 'Syringa', category: 'Nature', common: false },
  { word: 'toadflax', wiki: 'Toadflax', category: 'Nature', common: false },
  { word: 'trillium', wiki: 'Trillium', category: 'Nature', common: false },
  { word: 'turnsole', wiki: 'Turnsole', category: 'Nature', common: false },
  { word: 'verbena', wiki: 'Verbena', category: 'Nature', common: false },
  { word: 'viola', wiki: 'Viola', category: 'Music', common: false },
  { word: 'ait', wiki: 'Ait', category: 'Nature', article: 'an', common: false },
  { word: 'beck', wiki: 'Beck', category: 'Nature', common: false },
  { word: 'berm', wiki: 'Berm', category: 'Nature', common: false },
  { word: 'burn', wiki: 'Burn', category: 'Nature', common: false },
  { word: 'butte', wiki: 'Butte', category: 'Nature', common: false },
  { word: 'caatinga', wiki: 'Caatinga', category: 'Nature', common: false },
  { word: 'carse', wiki: 'Carse', category: 'Nature', common: false },
  { word: 'chine', wiki: 'Chine', category: 'Nature', common: false },
  { word: 'cirque', wiki: 'Cirque', category: 'Nature', common: false },
  { word: 'clove', wiki: 'Clove', category: 'Nature', common: false },
  { word: 'continent', wiki: 'Continent', category: 'Nature', common: false },
  { word: 'coulee', wiki: 'Coulee', category: 'Nature', common: false },
  { word: 'crevasse', wiki: 'Crevasse', category: 'Nature', common: false },
  { word: 'debouch', wiki: 'Debouch', category: 'Nature', common: false },
  { word: 'dene', wiki: 'Dene', category: 'Nature', common: false },
  { word: 'drumlin', wiki: 'Drumlin', category: 'Nature', common: false },
  { word: 'embouchure', wiki: 'Embouchure', category: 'Music', article: 'an', common: false },
  { word: 'escarpment', wiki: 'Escarpment', category: 'Nature', article: 'an', common: false },
  { word: 'esker', wiki: 'Esker', category: 'Nature', article: 'an', common: false },
  { word: 'estuary', wiki: 'Estuary', category: 'Nature', article: 'an', common: false },
  { word: 'fell', wiki: 'Fell', category: 'Nature', common: false },
  { word: 'geest', wiki: 'Geest', category: 'Nature', common: false },
  { word: 'glen', wiki: 'Glen', category: 'Nature', common: false },
  { word: 'graben', wiki: 'Graben', category: 'Nature', common: false },
  { word: 'grotto', wiki: 'Grotto', category: 'Nature', common: false },
  { word: 'gulch', wiki: 'Gulch', category: 'Nature', common: false },
  { word: 'headland', wiki: 'Headland', category: 'Nature', common: false },
  { word: 'hummock', wiki: 'Hummock', category: 'Nature', common: false },
  { word: 'inlet', wiki: 'Inlet', category: 'Nature', article: 'an', common: false },
  { word: 'inselberg', wiki: 'Inselberg', category: 'Nature', article: 'an', common: false },
  { word: 'islet', wiki: 'Islet', category: 'Nature', article: 'an', common: false },
  { word: 'isthmus', wiki: 'Isthmus', category: 'Nature', article: 'an', common: false },
  { word: 'kame', wiki: 'Kame', category: 'Nature', common: false },
  { word: 'land', wiki: 'Land', category: 'Nature', common: false },
  { word: 'linch', wiki: 'Linch', category: 'Nature', common: false },
  { word: 'meander', wiki: 'Meander', category: 'Nature', common: false },
  { word: 'mesa', wiki: 'Mesa', category: 'Nature', common: false },
  { word: 'moraine', wiki: 'Moraine', category: 'Nature', common: false },
  { word: 'nunatak', wiki: 'Nunatak', category: 'Nature', common: false },
  { word: 'peninsula', wiki: 'Peninsula', category: 'Nature', common: false },
  { word: 'piedmont', wiki: 'Piedmont', category: 'Nature', common: false },
  { word: 'promontory', wiki: 'Promontory', category: 'Nature', common: false },
  { word: 'ria', wiki: 'Ria', category: 'Nature', common: false },
  { word: 'shoal', wiki: 'Shoal', category: 'Nature', common: false },
  { word: 'skerry', wiki: 'Skerry', category: 'Nature', common: false },
  { word: 'strath', wiki: 'Strath', category: 'Nature', common: false },
  { word: 'wadi', wiki: 'Wadi', category: 'Nature', common: false },
  { word: 'anabranch', wiki: 'Anabranch', category: 'Nature', article: 'an', common: false },
  { word: 'aquifer', wiki: 'Aquifer', category: 'Nature', article: 'an', common: false },
  { word: 'billabong', wiki: 'Billabong', category: 'Nature', common: false },
  { word: 'charybdis', wiki: 'Charybdis', category: 'Nature', common: false },
  { word: 'floodgate', wiki: 'Floodgate', category: 'Nature', common: false },
  { word: 'harbor', wiki: 'Harbor', category: 'Nature', common: false },
  { word: 'leat', wiki: 'Leat', category: 'Nature', common: false },
  { word: 'loch', wiki: 'Loch', category: 'Nature', common: false },
  { word: 'rill', wiki: 'Rill', category: 'Nature', common: false },
  { word: 'sinkhole', wiki: 'Sinkhole', category: 'Nature', common: false },
  { word: 'sluice', wiki: 'Sluice', category: 'Nature', common: false },
  { word: 'strait', wiki: 'Strait', category: 'Nature', common: false },
  { word: 'waterway', wiki: 'Waterway', category: 'Nature', common: false },
  { word: 'whirlpool', wiki: 'Whirlpool', category: 'Nature', common: false },
  { word: 'ascochyta', wiki: 'Ascochyta', category: 'Nature', article: 'an', common: false },
  { word: 'aspergillus', wiki: 'Aspergillus', category: 'Nature', article: 'an', common: false },
  { word: 'conk', wiki: 'Conk', category: 'Nature', common: false },
  { word: 'cordyceps', wiki: 'Cordyceps', category: 'Nature', common: false },
  { word: 'cryptococcus', wiki: 'Cryptococcus', category: 'Nature', common: false },
  { word: 'ergot', wiki: 'Ergot', category: 'Nature', article: 'an', common: false },
  { word: 'fusarium', wiki: 'Fusarium', category: 'Nature', common: false },
  { word: 'mildew', wiki: 'Mildew', category: 'Nature', common: false },
  { word: 'mold', wiki: 'Mold', category: 'Places', common: false },
  { word: 'mycelium', wiki: 'Mycelium', category: 'Nature', common: false },
  { word: 'penicillium', wiki: 'Penicillium', category: 'Nature', common: false },
  { word: 'polypore', wiki: 'Polypore', category: 'Nature', common: false },
  { word: 'puccinia', wiki: 'Puccinia', category: 'Nature', common: false },
  { word: 'pycnidium', wiki: 'Pycnidium', category: 'Nature', common: false },
  { word: 'rust', wiki: 'Rust', category: 'Nature', common: false },
  { word: 'septoria', wiki: 'Septoria', category: 'Nature', common: false },
  { word: 'tremella', wiki: 'Tremella', category: 'Nature', common: false },
  { word: 'ustilago', wiki: 'Ustilago', category: 'Nature', article: 'an', common: false },
  { word: 'alabaster', wiki: 'Alabaster', category: 'Nature', article: 'an', common: false },
  { word: 'amphibolite', wiki: 'Amphibolite', category: 'Nature', article: 'an', common: false },
  { word: 'andesite', wiki: 'Andesite', category: 'Nature', article: 'an', common: false },
  { word: 'anorthosite', wiki: 'Anorthosite', category: 'Nature', article: 'an', common: false },
  { word: 'anthracite', wiki: 'Anthracite', category: 'Nature', article: 'an', common: false },
  { word: 'aplite', wiki: 'Aplite', category: 'Nature', article: 'an', common: false },
  { word: 'argillite', wiki: 'Argillite', category: 'Nature', article: 'an', common: false },
  { word: 'arkose', wiki: 'Arkose', category: 'Nature', article: 'an', common: false },
  { word: 'basalt', wiki: 'Basalt', category: 'Nature', common: false },
  { word: 'basanite', wiki: 'Basanite', category: 'Nature', common: false },
  { word: 'bedrock', wiki: 'Bedrock', category: 'Nature', common: false },
  { word: 'bluestone', wiki: 'Bluestone', category: 'Nature', common: false },
  { word: 'breccia', wiki: 'Breccia', category: 'Nature', common: false },
  { word: 'brownstone', wiki: 'Brownstone', category: 'Nature', common: false },
  { word: 'coal', wiki: 'Coal', category: 'Nature', common: false },
  { word: 'dacite', wiki: 'Dacite', category: 'Nature', common: false },
  { word: 'diabase', wiki: 'Diabase', category: 'Nature', common: false },
  { word: 'diorite', wiki: 'Diorite', category: 'Nature', common: false },
  { word: 'dunite', wiki: 'Dunite', category: 'Nature', common: false },
  { word: 'eclogite', wiki: 'Eclogite', category: 'Nature', article: 'an', common: false },
  { word: 'eucrite', wiki: 'Eucrite', category: 'Nature', article: 'an', common: false },
  { word: 'felsite', wiki: 'Felsite', category: 'Nature', common: false },
  { word: 'flint', wiki: 'Flint', category: 'Nature', common: false },
  { word: 'floatstone', wiki: 'Floatstone', category: 'Nature', common: false },
  { word: 'contrail', wiki: 'Contrail', category: 'Vehicles', common: false },
  { word: 'incus', wiki: 'Incus', category: 'Body', article: 'an', common: false },
  { word: 'pallium', wiki: 'Pallium', category: 'Weather', common: false },
  { word: 'spindrift', wiki: 'Spindrift', category: 'Weather', common: false },
  { word: 'ace', wiki: 'Ace', category: 'Sport', article: 'an', common: false },
  { word: 'backbencher', wiki: 'Backbencher', category: 'Sport', common: false },
  { word: 'balk', wiki: 'Balk', category: 'Sport', common: false },
  { word: 'bando', wiki: 'Bando', category: 'Sport', common: false },
  { word: 'bandy', wiki: 'Bandy', category: 'Sport', common: false },
  { word: 'bocce', wiki: 'Bocce', category: 'Sport', common: false },
  { word: 'bos', wiki: 'Bos', category: 'Sport', common: false },
  { word: 'brakeman', wiki: 'Brakeman', category: 'Jobs', common: false },
  { word: 'bullfighting', wiki: 'Bullfighting', category: 'Sport', common: false },
  { word: 'caboose', wiki: 'Caboose', category: 'Sport', common: false },
  { word: 'cannon', wiki: 'Cannon', category: 'Sport', common: false },
  { word: 'chelem', wiki: 'Chelem', category: 'Sport', common: false },
  { word: 'col', wiki: 'Col', category: 'Nature', common: false },
  { word: 'competition', wiki: 'Competition', category: 'Sport', common: false },
  { word: 'conference', wiki: 'Conference', category: 'Sport', common: false },
  { word: 'consolation', wiki: 'Consolation', category: 'Sport', common: false },
  { word: 'court', wiki: 'Court', category: 'Sport', common: false },
  { word: 'crew', wiki: 'Crew', category: 'Sport', common: false },
  { word: 'curling', wiki: 'Curling', category: 'Sport', common: false },
  { word: 'dal', wiki: 'Dal', category: 'Sport', common: false },
  { word: 'darts', wiki: 'Darts', category: 'Sport', common: false },
  { word: 'desultor', wiki: 'Desultor', category: 'Sport', common: false },
  { word: 'dissent', wiki: 'Dissent', category: 'Sport', common: false },
  { word: 'distance', wiki: 'Distance', category: 'Sport', common: false },
  { word: 'dressage', wiki: 'Dressage', category: 'Sport', common: false },
  { word: 'dynasty', wiki: 'Dynasty', category: 'Sport', common: false },
  { word: 'evolution', wiki: 'Evolution', category: 'Sport', article: 'an', common: false },
  { word: 'exhibition', wiki: 'Exhibition', category: 'Sport', article: 'an', common: false },
  { word: 'facial', wiki: 'Facial', category: 'Sport', common: false },
  { word: 'falconry', wiki: 'Falconry', category: 'Animals', common: false },
  { word: 'flight', wiki: 'Flight', category: 'Sport', common: false },
  { word: 'fumble', wiki: 'Fumble', category: 'Sport', common: false },
  { word: 'future', wiki: 'Future', category: 'Sport', common: false },
  { word: 'garbage', wiki: 'Garbage', category: 'Sport', common: false },
  { word: 'ghost', wiki: 'Ghost', category: 'Sport', common: false },
  { word: 'goalkeeper', wiki: 'Goalkeeper', category: 'Sport', common: false },
  { word: 'grind', wiki: 'Grind', category: 'Shapes', common: false },
  { word: 'hacker', wiki: 'Hacker', category: 'Sport', common: false },
  { word: 'hardwood', wiki: 'Hardwood', category: 'Sport', common: false },
  { word: 'homer', wiki: 'Homer', category: 'Sport', common: false },
  { word: 'howitzer', wiki: 'Howitzer', category: 'Sport', common: false },
  { word: 'hurling', wiki: 'Hurling', category: 'Sport', common: false },
  { word: 'intersection', wiki: 'Intersection', category: 'Sport', article: 'an', common: false },
  { word: 'kip-up', wiki: 'Kip-up', category: 'Sport', common: false },
  { word: 'knockout', wiki: 'Knockout', category: 'Sport', common: false },
  { word: 'laser', wiki: 'Laser', category: 'Sport', common: false },
  { word: 'lead', wiki: 'Lead', category: 'Sport', common: false },
  { word: 'man', wiki: 'Man', category: 'Sport', common: false },
  { word: 'match', wiki: 'Match', category: 'Sport', common: false },
  { word: 'meat', wiki: 'Meat', category: 'Food', common: false },
  { word: 'night', wiki: 'Night', category: 'Sport', common: false },
  { word: 'nomad', wiki: 'Nomad', category: 'Sport', common: false },
  { word: 'olympiad', wiki: 'Olympiad', category: 'Sport', article: 'an', common: false },
  { word: 'ore', wiki: 'Ore', category: 'Nature', article: 'an', common: false },
  { word: 'paddock', wiki: 'Paddock', category: 'Sport', common: false },
  { word: 'para-athletics', wiki: 'Para-athletics', category: 'Sport', common: false },
  { word: 'passer', wiki: 'Passer', category: 'Sport', common: false },
  { word: 'ped', wiki: 'Ped', category: 'Sport', common: false },
  { word: 'pentathlon', wiki: 'Pentathlon', category: 'Sport', common: false },
  { word: 'phi', wiki: 'Phi', category: 'Sport', common: false },
  { word: 'platoon', wiki: 'Platoon', category: 'Sport', common: false },
  { word: 'quarterstaff', wiki: 'Quarterstaff', category: 'Sport', common: false },
  { word: 'racing', wiki: 'Racing', category: 'Sport', common: false },
  { word: 'relay', wiki: 'Relay', category: 'Sport', common: false },
  { word: 'rodeo', wiki: 'Rodeo', category: 'Sport', common: false },
  { word: 'rotisserie', wiki: 'Rotisserie', category: 'Sport', common: false },
  { word: 'roto', wiki: 'Roto', category: 'Sport', common: false },
  { word: 'round', wiki: 'Round', category: 'Sport', common: false },
  { word: 'safety', wiki: 'Safety', category: 'Sport', common: false },
  { word: 'saint', wiki: 'Saint', category: 'Sport', common: false },
  { word: 'screamer', wiki: 'Screamer', category: 'Sport', common: false },
  { word: 'setter', wiki: 'Setter', category: 'Sport', common: false },
  { word: 'shin-kicking', wiki: 'Shin-kicking', category: 'Sport', common: false },
  { word: 'shinny', wiki: 'Shinny', category: 'Sport', common: false },
  { word: 'shinty', wiki: 'Shinty', category: 'Sport', common: false },
  { word: 'shutout', wiki: 'Shutout', category: 'Sport', common: false },
  { word: 'sin', wiki: 'Sin', category: 'Sport', common: false },
  { word: 'sortie', wiki: 'Sortie', category: 'Sport', common: false },
  { word: 'standing', wiki: 'Standing', category: 'Sport', common: false },
  { word: 'steroid', wiki: 'Steroid', category: 'Places', common: false },
  { word: 'string', wiki: 'String', category: 'Places', common: false },
  { word: 'supporter', wiki: 'Supporter', category: 'Sport', common: false },
  { word: 'survival', wiki: 'Survival', category: 'Sport', common: false },
  { word: 'switch', wiki: 'Switch', category: 'Sport', common: false },
  { word: 'synchro', wiki: 'Synchro', category: 'Sport', common: false },
  { word: 'tackler', wiki: 'Tackler', category: 'Clothes', common: false },
  { word: 'territory', wiki: 'Territory', category: 'Sport', common: false },
  { word: 'tetherball', wiki: 'Tetherball', category: 'Sport', common: false },
  { word: 'time', wiki: 'Time', category: 'Sport', common: false },
  { word: 'umpire', wiki: 'Umpire', category: 'Sport', article: 'an', common: false },
  { word: 'walkover', wiki: 'Walkover', category: 'Sport', common: false },
  { word: 'wat', wiki: 'Wat', category: 'Sport', common: false },
  { word: 'weight', wiki: 'Weight', category: 'Sport', common: false },
  { word: 'whitewash', wiki: 'Whitewash', category: 'Sport', common: false },
  { word: 'wing', wiki: 'Wing', category: 'Sport', common: false },
  { word: 'woodsman', wiki: 'Woodsman', category: 'Sport', common: false },
  { word: 'netball', wiki: 'Netball', category: 'Sport', common: false },
  { word: 'outfielder', wiki: 'Outfielder', category: 'Sport', article: 'an', common: false },
  { word: 'pushball', wiki: 'Pushball', category: 'Sport', common: false },
  { word: 'stickball', wiki: 'Stickball', category: 'Sport', common: false },
  { word: 'stoolball', wiki: 'Stoolball', category: 'Sport', common: false },
  { word: 'stroke', wiki: 'Stroke', category: 'Sport', common: false },
  { word: 'springboard', wiki: 'Springboard', category: 'Sport', common: false },
  { word: 'aliveness', wiki: 'Aliveness', category: 'Sport', article: 'an', common: false },
  { word: 'meteor', wiki: 'Meteor', category: 'Sport', common: false },
  { word: 'ninja', wiki: 'Ninja', category: 'Sport', common: false },
  { word: 'pankration', wiki: 'Pankration', category: 'Sport', common: false },
  { word: 'aerophone', wiki: 'Aerophone', category: 'Music', article: 'an', common: false },
  { word: 'alphorn', wiki: 'Alphorn', category: 'Music', article: 'an', common: false },
  { word: 'amati', wiki: 'Amati', category: 'Music', article: 'an', common: false },
  { word: 'aulos', wiki: 'Aulos', category: 'Music', article: 'an', common: false },
  { word: 'bassanello', wiki: 'Bassanello', category: 'Music', common: false },
  { word: 'bazooka', wiki: 'Bazooka', category: 'Music', common: false },
  { word: 'bonang', wiki: 'Bonang', category: 'Music', common: false },
  { word: 'buccina', wiki: 'Buccina', category: 'Music', common: false },
  { word: 'calliope', wiki: 'Calliope', category: 'Music', common: false },
  { word: 'cantaro', wiki: 'Cantaro', category: 'Music', common: false },
  { word: 'carillon', wiki: 'Carillon', category: 'Music', common: false },
  { word: 'celesta', wiki: 'Celesta', category: 'Music', common: false },
  { word: 'chalumeau', wiki: 'Chalumeau', category: 'Music', common: false },
  { word: 'clavichord', wiki: 'Clavichord', category: 'Music', common: false },
  { word: 'clavicytherium', wiki: 'Clavicytherium', category: 'Music', common: false },
  { word: 'claviharp', wiki: 'Claviharp', category: 'Music', common: false },
  { word: 'conch', wiki: 'Conch', category: 'Music', common: false },
  { word: 'conga', wiki: 'Conga', category: 'Music', common: false },
  { word: 'cowbell', wiki: 'Cowbell', category: 'Clothes', common: false },
  { word: 'cromorne', wiki: 'Cromorne', category: 'Music', common: false },
  { word: 'dulcian', wiki: 'Dulcian', category: 'Music', common: false },
  { word: 'flattop', wiki: 'Flattop', category: 'Music', common: false },
  { word: 'flugelhorn', wiki: 'Flugelhorn', category: 'Music', common: false },
  { word: 'flutina', wiki: 'Flutina', category: 'Music', common: false },
  { word: 'glockenspiel', wiki: 'Glockenspiel', category: 'Music', common: false },
  { word: 'harmonichord', wiki: 'Harmonichord', category: 'Music', common: false },
  { word: 'hornpipe', wiki: 'Hornpipe', category: 'Music', common: false },
  { word: 'kantele', wiki: 'Kantele', category: 'Music', common: false },
  { word: 'kazoo', wiki: 'Kazoo', category: 'Music', common: false },
  { word: 'kettledrum', wiki: 'Kettledrum', category: 'Music', common: false },
  { word: 'kissar', wiki: 'Kissar', category: 'Music', common: false },
  { word: 'lur', wiki: 'Lur', category: 'Music', common: false },
  { word: 'mandola', wiki: 'Mandola', category: 'Music', common: false },
  { word: 'mandolin-banjo', wiki: 'Mandolin-banjo', category: 'Music', common: false },
  { word: 'mandora', wiki: 'Mandora', category: 'Music', common: false },
  { word: 'melodica', wiki: 'Melodica', category: 'Music', common: false },
  { word: 'monochord', wiki: 'Monochord', category: 'Music', common: false },
  { word: 'morsing', wiki: 'Morsing', category: 'Music', common: false },
  { word: 'nabal', wiki: 'Nabal', category: 'Music', common: false },
  { word: 'ocarina', wiki: 'Ocarina', category: 'Music', article: 'an', common: false },
  { word: 'octavina', wiki: 'Octavina', category: 'Music', article: 'an', common: false },
  { word: 'octobass', wiki: 'Octobass', category: 'Music', article: 'an', common: false },
  { word: 'ophicleide', wiki: 'Ophicleide', category: 'Music', article: 'an', common: false },
  { word: 'orchestrion', wiki: 'Orchestrion', category: 'Music', article: 'an', common: false },
  { word: 'organette', wiki: 'Organette', category: 'Music', article: 'an', common: false },
  { word: 'organistrum', wiki: 'Organistrum', category: 'Music', article: 'an', common: false },
  { word: 'orpharion', wiki: 'Orpharion', category: 'Music', article: 'an', common: false },
  { word: 'pandura', wiki: 'Pandura', category: 'Music', common: false },
  { word: 'pantaleon', wiki: 'Pantaleon', category: 'Music', common: false },
  { word: 'phorminx', wiki: 'Phorminx', category: 'Music', common: false },
  { word: 'pipa', wiki: 'Pipa', category: 'Music', common: false },
  { word: 'plectrum', wiki: 'Plectrum', category: 'Home', common: false },
  { word: 'psaltery', wiki: 'Psaltery', category: 'Music', common: false },
  { word: 'pungi', wiki: 'Pungi', category: 'Music', common: false },
  { word: 'rackett', wiki: 'Rackett', category: 'Music', common: false },
  { word: 'rebab', wiki: 'Rebab', category: 'Music', common: false },
  { word: 'rebec', wiki: 'Rebec', category: 'Music', common: false },
  { word: 'rhodes', wiki: 'Rhodes', category: 'Nature', common: false },
  { word: 'sarangi', wiki: 'Sarangi', category: 'Music', common: false },
  { word: 'sarod', wiki: 'Sarod', category: 'Music', common: false },
  { word: 'sarrusophone', wiki: 'Sarrusophone', category: 'Weather', common: false },
  { word: 'saxhorn', wiki: 'Saxhorn', category: 'Music', common: false },
  { word: 'saxotromba', wiki: 'Saxotromba', category: 'Music', common: false },
  { word: 'saxtuba', wiki: 'Saxtuba', category: 'Music', common: false },
  { word: 'scabellum', wiki: 'Scabellum', category: 'Music', common: false },
  { word: 'serinette', wiki: 'Serinette', category: 'Music', common: false },
  { word: 'shawm', wiki: 'Shawm', category: 'Music', common: false },
  { word: 'spina', wiki: 'Spina', category: 'Music', common: false },
  { word: 'spinet', wiki: 'Spinet', category: 'Music', common: false },
  { word: 'stradivarius', wiki: 'Stradivarius', category: 'Music', common: false },
  { word: 'synthesizer', wiki: 'Synthesizer', category: 'Music', common: false },
  { word: 'syrinx', wiki: 'Syrinx', category: 'Music', common: false },
  { word: 'tar', wiki: 'Tar', category: 'Music', common: false },
  { word: 'telharmonium', wiki: 'Telharmonium', category: 'Body', common: false },
  { word: 'tenoroon', wiki: 'Tenoroon', category: 'Music', common: false },
  { word: 'terpodion', wiki: 'Terpodion', category: 'Music', common: false },
  { word: 'theorbo', wiki: 'Theorbo', category: 'Music', common: false },
  { word: 'tibia', wiki: 'Tibia', category: 'Body', common: false },
  { word: 'timpani', wiki: 'Timpani', category: 'Music', common: false },
  { word: 'tiple', wiki: 'Tiple', category: 'Music', common: false },
  { word: 'trigonon', wiki: 'Trigonon', category: 'Music', common: false },
  { word: 'vielle', wiki: 'Vielle', category: 'Music', common: false },
  { word: 'vihuela', wiki: 'Vihuela', category: 'Music', common: false },
  { word: 'viol', wiki: 'Viol', category: 'Music', common: false },
  { word: 'actuary', wiki: 'Actuary', category: 'Jobs', article: 'an', common: false },
  { word: 'airman', wiki: 'Airman', category: 'Jobs', article: 'an', common: false },
  { word: 'amanuensis', wiki: 'Amanuensis', category: 'Jobs', article: 'an', common: false },
  { word: 'animator', wiki: 'Animator', category: 'Jobs', article: 'an', common: false },
  { word: 'announcer', wiki: 'Announcer', category: 'Jobs', article: 'an', common: false },
  { word: 'arborist', wiki: 'Arborist', category: 'Jobs', article: 'an', common: false },
  { word: 'artisan', wiki: 'Artisan', category: 'Jobs', article: 'an', common: false },
  { word: 'augur', wiki: 'Augur', category: 'Jobs', article: 'an', common: false },
  { word: 'bagger', wiki: 'Bagger', category: 'Places', common: false },
  { word: 'bailiff', wiki: 'Bailiff', category: 'Jobs', common: false },
  { word: 'baler', wiki: 'Baler', category: 'Jobs', common: false },
  { word: 'bard', wiki: 'Bard', category: 'Jobs', common: false },
  { word: 'bartender', wiki: 'Bartender', category: 'Jobs', common: false },
  { word: 'beek', wiki: 'Beek', category: 'Jobs', common: false },
  { word: 'beekeeper', wiki: 'Beekeeper', category: 'Jobs', common: false },
  { word: 'bellhop', wiki: 'Bellhop', category: 'Jobs', common: false },
  { word: 'bodyguard', wiki: 'Bodyguard', category: 'Jobs', common: false },
  { word: 'boilermaker', wiki: 'Boilermaker', category: 'Jobs', common: false },
  { word: 'bookmaker', wiki: 'Bookmaker', category: 'Jobs', common: false },
  { word: 'bouncer', wiki: 'Bouncer', category: 'Jobs', common: false },
  { word: 'bricklayer', wiki: 'Bricklayer', category: 'Jobs', common: false },
  { word: 'bullocky', wiki: 'Bullocky', category: 'Jobs', common: false },
  { word: 'busser', wiki: 'Busser', category: 'Jobs', common: false },
  { word: 'cannoneer', wiki: 'Cannoneer', category: 'Jobs', common: false },
  { word: 'carhop', wiki: 'Carhop', category: 'Jobs', common: false },
  { word: 'cartoonist', wiki: 'Cartoonist', category: 'Jobs', common: false },
  { word: 'cartulary', wiki: 'Cartulary', category: 'School', common: false },
  { word: 'chauffeur', wiki: 'Chauffeur', category: 'Jobs', common: false },
  { word: 'cinematographer', wiki: 'Cinematographer', category: 'Jobs', common: false },
  { word: 'cleaner', wiki: 'Cleaner', category: 'Jobs', common: false },
  { word: 'clicker', wiki: 'Clicker', category: 'Animals', common: false },
  { word: 'clockmaker', wiki: 'Clockmaker', category: 'Jobs', common: false },
  { word: 'coachman', wiki: 'Coachman', category: 'Vehicles', common: false },
  { word: 'colorist', wiki: 'Colorist', category: 'Colors', common: false },
  { word: 'columnist', wiki: 'Columnist', category: 'Jobs', common: false },
  { word: 'comedian', wiki: 'Comedian', category: 'Jobs', common: false },
  { word: 'concierge', wiki: 'Concierge', category: 'Places', common: false },
  { word: 'conquistador', wiki: 'Conquistador', category: 'Jobs', common: false },
  { word: 'coroner', wiki: 'Coroner', category: 'Jobs', common: false },
  { word: 'costermonger', wiki: 'Costermonger', category: 'Food', common: false },
  { word: 'courtier', wiki: 'Courtier', category: 'Jobs', common: false },
  { word: 'cowboy', wiki: 'Cowboy', category: 'Jobs', common: false },
  { word: 'critic', wiki: 'Critic', category: 'Jobs', common: false },
  { word: 'cupbearer', wiki: 'Cupbearer', category: 'Jobs', common: false },
  { word: 'curator', wiki: 'Curator', category: 'Jobs', common: false },
  { word: 'deacon', wiki: 'Deacon', category: 'Jobs', common: false },
  { word: 'deputy', wiki: 'Deputy', category: 'Jobs', common: false },
  { word: 'derrick', wiki: 'Derrick', category: 'Jobs', common: false },
  { word: 'designer', wiki: 'Designer', category: 'Jobs', common: false },
  { word: 'dietitian', wiki: 'Dietitian', category: 'Jobs', common: false },
  { word: 'dipper', wiki: 'Dipper', category: 'Jobs', common: false },
  { word: 'dispatcher', wiki: 'Dispatcher', category: 'Jobs', common: false },
  { word: 'dispenser', wiki: 'Dispenser', category: 'Jobs', common: false },
  { word: 'drayman', wiki: 'Drayman', category: 'Jobs', common: false },
  { word: 'executioner', wiki: 'Executioner', category: 'Jobs', article: 'an', common: false },
  { word: 'expert', wiki: 'Expert', category: 'Jobs', article: 'an', common: false },
  { word: 'famulus', wiki: 'Famulus', category: 'Jobs', common: false },
  { word: 'farrier', wiki: 'Farrier', category: 'Jobs', common: false },
  { word: 'flamen', wiki: 'Flamen', category: 'Jobs', common: false },
  { word: 'fluffer', wiki: 'Fluffer', category: 'Jobs', common: false },
  { word: 'forester', wiki: 'Forester', category: 'Jobs', common: false },
  { word: 'gaberlunzie', wiki: 'Gaberlunzie', category: 'Jobs', common: false },
  { word: 'gazetteer', wiki: 'Gazetteer', category: 'Jobs', common: false },
  { word: 'geographer', wiki: 'Geographer', category: 'Jobs', common: false },
  { word: 'gillie', wiki: 'Gillie', category: 'Jobs', common: false },
  { word: 'glazier', wiki: 'Glazier', category: 'Jobs', common: false },
  { word: 'g-man', wiki: 'G-man', category: 'Jobs', common: false },
  { word: 'goatherd', wiki: 'Goatherd', category: 'Jobs', common: false },
  { word: 'gopher', wiki: 'Gopher', category: 'Jobs', common: false },
  { word: 'governess', wiki: 'Governess', category: 'Home', common: false },
  { word: 'gravedigger', wiki: 'Gravedigger', category: 'Jobs', common: false },
  { word: 'greengrocer', wiki: 'Greengrocer', category: 'Jobs', common: false },
  { word: 'guru', wiki: 'Guru', category: 'Jobs', common: false },
  { word: 'hamal', wiki: 'Hamal', category: 'Jobs', common: false },
  { word: 'hammersmith', wiki: 'Hammersmith', category: 'Jobs', common: false },
  { word: 'hewer', wiki: 'Hewer', category: 'Nature', common: false },
  { word: 'hostie', wiki: 'Hostie', category: 'Jobs', common: false },
  { word: 'houseboy', wiki: 'Houseboy', category: 'Jobs', common: false },
  { word: 'humorist', wiki: 'Humorist', category: 'School', common: false },
  { word: 'husbandman', wiki: 'Husbandman', category: 'Jobs', common: false },
  { word: 'inquisitor', wiki: 'Inquisitor', category: 'Jobs', article: 'an', common: false },
  { word: 'investor', wiki: 'Investor', category: 'Jobs', article: 'an', common: false },
  { word: 'ironmaster', wiki: 'Ironmaster', category: 'Jobs', article: 'an', common: false },
  { word: 'ironworker', wiki: 'Ironworker', category: 'Jobs', article: 'an', common: false },
  { word: 'jackaroo', wiki: 'Jackaroo', category: 'Jobs', common: false },
  { word: 'jurist', wiki: 'Jurist', category: 'Jobs', common: false },
  { word: 'kidney', wiki: 'Kidney', category: 'Body', common: false },
  { word: 'knacker', wiki: 'Knacker', category: 'Jobs', common: false },
  { word: 'knocker-up', wiki: 'Knocker-up', category: 'Jobs', common: false },
  { word: 'laborer', wiki: 'Laborer', category: 'Jobs', common: false },
  { word: 'lady-in-waiting', wiki: 'Lady-in-waiting', category: 'Jobs', common: false },
  { word: 'lamplighter', wiki: 'Lamplighter', category: 'Jobs', common: false },
  { word: 'lapidary', wiki: 'Lapidary', category: 'Clothes', common: false },
  { word: 'machinist', wiki: 'Machinist', category: 'Jobs', common: false },
  { word: 'magistrate', wiki: 'Magistrate', category: 'Jobs', common: false },
  { word: 'mahout', wiki: 'Mahout', category: 'Jobs', common: false },
  { word: 'maid', wiki: 'Maid', category: 'Jobs', common: false },
  { word: 'mali', wiki: 'Mali', category: 'Jobs', common: false },
  { word: 'marksman', wiki: 'Marksman', category: 'Jobs', common: false },
  { word: 'milkmaid', wiki: 'Milkmaid', category: 'Jobs', common: false },
  { word: 'miller', wiki: 'Miller', category: 'Jobs', common: false },
  { word: 'millwright', wiki: 'Millwright', category: 'Jobs', common: false },
  { word: 'missionary', wiki: 'Missionary', category: 'Jobs', common: false },
  { word: 'moneyer', wiki: 'Moneyer', category: 'Jobs', common: false },
  { word: 'monk', wiki: 'Monk', category: 'Jobs', common: false },
  { word: 'muezzin', wiki: 'Muezzin', category: 'Jobs', common: false },
  { word: 'nanny', wiki: 'Nanny', category: 'Jobs', common: false },
  { word: 'nippy', wiki: 'Nippy', category: 'Jobs', common: false },
  { word: 'novelist', wiki: 'Novelist', category: 'Jobs', common: false },
  { word: 'nutritionist', wiki: 'Nutritionist', category: 'Jobs', common: false },
  { word: 'ombudsman', wiki: 'Ombudsman', category: 'Jobs', article: 'an', common: false },
  { word: 'paratrooper', wiki: 'Paratrooper', category: 'Jobs', common: false },
  { word: 'parson', wiki: 'Parson', category: 'Jobs', common: false },
  { word: 'pastor', wiki: 'Pastor', category: 'Jobs', common: false },
  { word: 'pawnbroker', wiki: 'Pawnbroker', category: 'Jobs', common: false },
  { word: 'peddler', wiki: 'Peddler', category: 'Jobs', common: false },
  { word: 'perfumer', wiki: 'Perfumer', category: 'Jobs', common: false },
  { word: 'plasterer', wiki: 'Plasterer', category: 'Jobs', common: false },
  { word: 'playwright', wiki: 'Playwright', category: 'Jobs', common: false },
  { word: 'politician', wiki: 'Politician', category: 'Jobs', common: false },
  { word: 'postmaster', wiki: 'Postmaster', category: 'Jobs', common: false },
  { word: 'preacher', wiki: 'Preacher', category: 'Jobs', common: false },
  { word: 'profession', wiki: 'Profession', category: 'Jobs', common: false },
  { word: 'projectionist', wiki: 'Projectionist', category: 'Jobs', common: false },
  { word: 'puppeteer', wiki: 'Puppeteer', category: 'Jobs', common: false },
  { word: 'pyrotechnician', wiki: 'Pyrotechnician', category: 'Jobs', common: false },
  { word: 'radiographer', wiki: 'Radiographer', category: 'Jobs', common: false },
  { word: 'rafter', wiki: 'Rafter', category: 'Jobs', common: false },
  { word: 'roofer', wiki: 'Roofer', category: 'Jobs', common: false },
  { word: 'roustabout', wiki: 'Roustabout', category: 'Jobs', common: false },
  { word: 'sacristan', wiki: 'Sacristan', category: 'Jobs', common: false },
  { word: 'sailmaker', wiki: 'Sailmaker', category: 'Jobs', common: false },
  { word: 'schoolmaster', wiki: 'Schoolmaster', category: 'Jobs', common: false },
  { word: 'screenwriter', wiki: 'Screenwriter', category: 'Jobs', common: false },
  { word: 'scribe', wiki: 'Scribe', category: 'Jobs', common: false },
  { word: 'sharpshooter', wiki: 'Sharpshooter', category: 'Jobs', common: false },
  { word: 'sheriff', wiki: 'Sheriff', category: 'Jobs', common: false },
  { word: 'shopkeeper', wiki: 'Shopkeeper', category: 'Places', common: false },
  { word: 'showman', wiki: 'Showman', category: 'Jobs', common: false },
  { word: 'signalman', wiki: 'Signalman', category: 'Jobs', common: false },
  { word: 'signwriter', wiki: 'Signwriter', category: 'Jobs', common: false },
  { word: 'sommelier', wiki: 'Sommelier', category: 'Jobs', common: false },
  { word: 'stagehand', wiki: 'Stagehand', category: 'Jobs', common: false },
  { word: 'stockbroker', wiki: 'Stockbroker', category: 'Jobs', common: false },
  { word: 'storekeeper', wiki: 'Storekeeper', category: 'Jobs', common: false },
  { word: 'strapper', wiki: 'Strapper', category: 'Jobs', common: false },
  { word: 'sutler', wiki: 'Sutler', category: 'Jobs', common: false },
  { word: 'syndic', wiki: 'Syndic', category: 'Jobs', common: false },
  { word: 'teamster', wiki: 'Teamster', category: 'Jobs', common: false },
  { word: 'telegraphist', wiki: 'Telegraphist', category: 'Jobs', common: false },
  { word: 'tinker', wiki: 'Tinker', category: 'Jobs', common: false },
  { word: 'tobacconist', wiki: 'Tobacconist', category: 'Jobs', common: false },
  { word: 'treasurer', wiki: 'Treasurer', category: 'Jobs', common: false },
  { word: 'valet', wiki: 'Valet', category: 'Jobs', common: false },
  { word: 'vassal', wiki: 'Vassal', category: 'Jobs', common: false },
  { word: 'warehouseman', wiki: 'Warehouseman', category: 'Jobs', common: false },
  { word: 'washerwoman', wiki: 'Washerwoman', category: 'Jobs', common: false },
  { word: 'wheelwright', wiki: 'Wheelwright', category: 'Jobs', common: false },
  { word: 'whip', wiki: 'Whip', category: 'Home', common: false },
  { word: 'antihelix', wiki: 'Antihelix', category: 'Body', article: 'an', common: false },
  { word: 'antitragus', wiki: 'Antitragus', category: 'Body', article: 'an', common: false },
  { word: 'bladder', wiki: 'Bladder', category: 'Body', common: false },
  { word: 'blade', wiki: 'Blade', category: 'Home', common: false },
  { word: 'bunion', wiki: 'Bunion', category: 'Body', common: false },
  { word: 'cilium', wiki: 'Cilium', category: 'Body', common: false },
  { word: 'cochlea', wiki: 'Cochlea', category: 'Body', common: false },
  { word: 'concha', wiki: 'Concha', category: 'Food', common: false },
  { word: 'dimple', wiki: 'Dimple', category: 'Body', common: false },
  { word: 'endodermis', wiki: 'Endodermis', category: 'Nature', article: 'an', common: false },
  { word: 'epidermis', wiki: 'Epidermis', category: 'Body', article: 'an', common: false },
  { word: 'joint', wiki: 'Joint', category: 'Body', common: false },
  { word: 'manhole', wiki: 'Manhole', category: 'Body', common: false },
  { word: 'nerve', wiki: 'Nerve', category: 'Body', common: false },
  { word: 'oviduct', wiki: 'Oviduct', category: 'Body', article: 'an', common: false },
  { word: 'synapse', wiki: 'Synapse', category: 'Places', common: false },
  { word: 'tibiotarsus', wiki: 'Tibiotarsus', category: 'Body', common: false },
  { word: 'asymptote', wiki: 'Asymptote', category: 'Shapes', article: 'an', common: false },
  { word: 'cardioid', wiki: 'Cardioid', category: 'Shapes', common: false },
  { word: 'equator', wiki: 'Equator', category: 'Shapes', article: 'an', common: false },
  { word: 'hypercone', wiki: 'Hypercone', category: 'Shapes', common: false },
  { word: 'lens', wiki: 'Lens', category: 'Shapes', common: false },
  { word: 'n-sphere', wiki: 'N-sphere', category: 'Shapes', common: false },
  { word: 'shape', wiki: 'Shape', category: 'Shapes', common: false },
  { word: 'swastika', wiki: 'Swastika', category: 'Shapes', common: false },
  { word: 'tangent', wiki: 'Tangent', category: 'Shapes', common: false },
  { word: 'tesseract', wiki: 'Tesseract', category: 'Shapes', common: false },
  { word: 'trapezoid', wiki: 'Trapezoid', category: 'Shapes', common: false },
  { word: 'chiliagon', wiki: 'Chiliagon', category: 'Shapes', common: false },
  { word: 'dodecagon', wiki: 'Dodecagon', category: 'Shapes', common: false },
  { word: 'hendecagon', wiki: 'Hendecagon', category: 'Shapes', common: false },
  { word: 'nonagon', wiki: 'Nonagon', category: 'Shapes', common: false },
  { word: 'pentadecagon', wiki: 'Pentadecagon', category: 'Shapes', common: false },
  { word: 'pentagram', wiki: 'Pentagram', category: 'Shapes', common: false },
  { word: 'antiprism', wiki: 'Antiprism', category: 'Shapes', article: 'an', common: false },
  { word: 'cuboctahedron', wiki: 'Cuboctahedron', category: 'Shapes', common: false },
  { word: 'decahedron', wiki: 'Decahedron', category: 'Shapes', common: false },
  { word: 'disphenoid', wiki: 'Disphenoid', category: 'Shapes', common: false },
  { word: 'hendecahedron', wiki: 'Hendecahedron', category: 'Shapes', common: false },
  { word: 'heptahedron', wiki: 'Heptahedron', category: 'Shapes', common: false },
  { word: 'pentahedron', wiki: 'Pentahedron', category: 'Shapes', common: false },
  { word: 'polyhedron', wiki: 'Polyhedron', category: 'Shapes', common: false },
  { word: 'tetrahedron', wiki: 'Tetrahedron', category: 'Shapes', common: false },
  { word: 'trapezohedron', wiki: 'Trapezohedron', category: 'Shapes', common: false },
  { word: 'amethyst', wiki: 'Amethyst', category: 'Nature', article: 'an', common: false },
  { word: 'ash', wiki: 'Ash', category: 'Colors', article: 'an', common: false },
  { word: 'azorubine', wiki: 'Azorubine', category: 'Colors', article: 'an', common: false },
  { word: 'dye', wiki: 'Dye', category: 'Colors', common: false },
  { word: 'ebony', wiki: 'Ebony', category: 'Colors', article: 'an', common: false },
  { word: 'honeysuckle', wiki: 'Honeysuckle', category: 'Colors', common: false },
  { word: 'obsidian', wiki: 'Obsidian', category: 'Colors', article: 'an', common: false },
  { word: 'onyx', wiki: 'Onyx', category: 'Colors', article: 'an', common: false },
  { word: 'pastel', wiki: 'Pastel', category: 'Colors', common: false },
  { word: 'pearl', wiki: 'Pearl', category: 'Animals', common: false },
  { word: 'unicorn', wiki: 'Unicorn', category: 'Colors', article: 'an', common: false },
  { word: 'wool', wiki: 'Wool', category: 'Clothes', common: false },
];
