// Curated vocabulary. Each entry maps a child-friendly label to the English
// Wikipedia article whose lead image reliably depicts that word. Keeping the
// article title explicit is what prevents the picture/word mismatches that free
// text image search produces.

/**
 * `wiki`     English Wikipedia article whose lead image depicts the word.
 * `commons`  Explicit Commons file, when the article's lead image is a poor
 *            match (e.g. the "Star" article leads with a photo of the Sun).
 * `direct`   Fully hand-specified image + credit, for the rare word neither
 *            source covers well.
 *
 * @typedef {{word:string, wiki?:string, category:string, article?:'a'|'an',
 *            plural?:boolean, commons?:string,
 *            direct?:{url:string,author:string,license:string,licenseUrl:string,source:string}}} Entry
 */

/** @type {Entry[]} */
export const vocabulary = [
  // ---------------------------------------------------------------- Food
  { word: 'apple', wiki: 'Apple', category: 'Food', article: 'an' },
  { word: 'banana', wiki: 'Banana', category: 'Food' },
  { word: 'orange', wiki: 'Orange (fruit)', category: 'Food', article: 'an' },
  { word: 'lemon', wiki: 'Lemon', category: 'Food' },
  { word: 'grapes', wiki: 'Grape', category: 'Food', plural: true },
  { word: 'watermelon', wiki: 'Watermelon', category: 'Food' },
  { word: 'strawberry', wiki: 'Strawberry', category: 'Food' },
  { word: 'cherry', wiki: 'Cherry', category: 'Food' },
  { word: 'peach', wiki: 'Peach', category: 'Food', commons: 'Autumn Red peaches.jpg' },
  { word: 'pear', wiki: 'Pear', category: 'Food' },
  { word: 'pineapple', wiki: 'Pineapple', category: 'Food' },
  { word: 'mango', wiki: 'Mango', category: 'Food' },
  { word: 'carrot', wiki: 'Carrot', category: 'Food' },
  { word: 'corn', wiki: 'Maize', category: 'Food', mass: true },
  { word: 'tomato', wiki: 'Tomato', category: 'Food' },
  { word: 'potato', wiki: 'Potato', category: 'Food' },
  { word: 'onion', wiki: 'Onion', category: 'Food', article: 'an' },
  { word: 'bread', wiki: 'Bread', category: 'Food', mass: true },
  { word: 'cheese', wiki: 'Cheese', category: 'Food', mass: true },
  { word: 'egg', wiki: 'Egg as food', category: 'Food', article: 'an' },
  { word: 'cookie', wiki: 'Cookie', category: 'Food' },
  { word: 'cake', wiki: 'Cake', category: 'Food' },
  { word: 'milk', wiki: 'Milk', category: 'Food', mass: true },
  { word: 'rice', wiki: 'Rice', category: 'Food', mass: true },
  { word: 'honey', wiki: 'Honey', category: 'Food', mass: true },
  { word: 'ice cream', wiki: 'Ice cream', category: 'Food', mass: true },

  // ------------------------------------------------------------- Animals
  { word: 'cat', wiki: 'Cat', category: 'Animals' },
  { word: 'dog', wiki: 'Dog', category: 'Animals' },
  { word: 'rabbit', wiki: 'Rabbit', category: 'Animals' },
  { word: 'mouse', wiki: 'Mouse', category: 'Animals' },
  { word: 'horse', wiki: 'Horse', category: 'Animals' },
  { word: 'cow', wiki: 'Cattle', category: 'Animals' },
  { word: 'pig', wiki: 'Pig', category: 'Animals' },
  { word: 'sheep', wiki: 'Sheep', category: 'Animals' },
  { word: 'goat', wiki: 'Goat', category: 'Animals' },
  { word: 'fox', wiki: 'Red fox', category: 'Animals' },
  { word: 'bear', wiki: 'Bear', category: 'Animals' },
  { word: 'panda', wiki: 'Giant panda', category: 'Animals' },
  { word: 'lion', wiki: 'Lion', category: 'Animals' },
  { word: 'tiger', wiki: 'Tiger', category: 'Animals' },
  { word: 'elephant', wiki: 'Elephant', category: 'Animals', article: 'an' },
  { word: 'giraffe', wiki: 'Giraffe', category: 'Animals' },
  { word: 'zebra', wiki: 'Zebra', category: 'Animals' },
  { word: 'monkey', wiki: 'Monkey', category: 'Animals' },
  { word: 'kangaroo', wiki: 'Kangaroo', category: 'Animals' },
  { word: 'deer', wiki: 'Deer', category: 'Animals' },
  { word: 'squirrel', wiki: 'Squirrel', category: 'Animals' },
  { word: 'frog', wiki: 'Frog', category: 'Animals' },
  { word: 'snake', wiki: 'Snake', category: 'Animals' },
  { word: 'turtle', wiki: 'Turtle', category: 'Animals' },
  { word: 'chicken', wiki: 'Chicken', category: 'Animals' },
  { word: 'duck', wiki: 'Duck', category: 'Animals' },
  { word: 'owl', wiki: 'Owl', category: 'Animals', article: 'an' },
  { word: 'penguin', wiki: 'Penguin', category: 'Animals' },
  { word: 'parrot', wiki: 'Parrot', category: 'Animals' },
  { word: 'butterfly', wiki: 'Butterfly', category: 'Animals' },
  { word: 'bee', wiki: 'Bee', category: 'Animals' },
  { word: 'fish', wiki: 'Fish', category: 'Animals' },

  // -------------------------------------------------------------- School
  { word: 'pen', wiki: 'Pen', category: 'School' },
  { word: 'pencil', wiki: 'Pencil', category: 'School' },
  { word: 'eraser', wiki: 'Eraser', category: 'School', article: 'an' },
  { word: 'book', wiki: 'Book', category: 'School' },
  { word: 'notebook', wiki: 'Notebook', category: 'School' },
  { word: 'backpack', wiki: 'Backpack', category: 'School' },
  { word: 'ruler', wiki: 'Ruler', category: 'School' },
  { word: 'scissors', wiki: 'Scissors', category: 'School', plural: true },
  { word: 'crayon', wiki: 'Crayon', category: 'School' },
  { word: 'paper', wiki: 'Paper', category: 'School', mass: true },
  { word: 'glue stick', wiki: 'Glue stick', category: 'School' },
  { word: 'chalk', wiki: 'Chalk', category: 'School', mass: true, commons: 'Colored chalks (3391214973).jpg' },
  { word: 'blackboard', wiki: 'Blackboard', category: 'School' },
  { word: 'globe', wiki: 'Globe', category: 'School' },
  { word: 'clock', wiki: 'Clock', category: 'School' },
  { word: 'desk', wiki: 'Desk', category: 'School' },
  { word: 'chair', wiki: 'Chair', category: 'School' },
  { word: 'bell', wiki: 'Bell', category: 'School' },

  // ---------------------------------------------------------------- Home
  { word: 'cup', wiki: 'Cup', category: 'Home' },
  {
    word: 'plate',
    category: 'Home',
    // The "Plate (dishware)" article leads with a botanical print, not a plate.
    direct: {
      url: 'https://live.staticflickr.com/2480/3668547763_24ae3b3361_b.jpg',
      author: 'David Masters',
      license: 'CC BY 2.0',
      licenseUrl: 'https://creativecommons.org/licenses/by/2.0/',
      source: 'https://www.flickr.com/photos/davidmasters/3668547763',
    },
  },
  { word: 'spoon', wiki: 'Spoon', category: 'Home' },
  { word: 'fork', wiki: 'Fork', category: 'Home' },
  { word: 'knife', wiki: 'Knife', category: 'Home' },
  { word: 'bowl', wiki: 'Bowl', category: 'Home' },
  { word: 'bottle', wiki: 'Bottle', category: 'Home' },
  { word: 'lamp', wiki: 'Light fixture', category: 'Home' },
  { word: 'key', wiki: 'Key (lock)', category: 'Home' },
  { word: 'door', wiki: 'Door', category: 'Home' },
  { word: 'window', wiki: 'Window', category: 'Home' },
  { word: 'bed', wiki: 'Bed', category: 'Home' },
  { word: 'table', wiki: 'Table (furniture)', category: 'Home' },
  { word: 'sofa', wiki: 'Couch', category: 'Home' },
  { word: 'mirror', wiki: 'Mirror', category: 'Home' },
  { word: 'towel', wiki: 'Towel', category: 'Home' },
  { word: 'soap', wiki: 'Soap', category: 'Home', mass: true },
  { word: 'toothbrush', wiki: 'Toothbrush', category: 'Home' },
  { word: 'comb', wiki: 'Comb', category: 'Home' },
  { word: 'basket', wiki: 'Basket', category: 'Home' },
  { word: 'umbrella', wiki: 'Umbrella', category: 'Home', article: 'an' },
  { word: 'phone', wiki: 'Mobile phone', category: 'Home' },
  { word: 'camera', wiki: 'Camera', category: 'Home' },
  { word: 'television', wiki: 'Television', category: 'Home' },

  // -------------------------------------------------------------- Places
  { word: 'house', wiki: 'House', category: 'Places' },
  { word: 'school', wiki: 'School', category: 'Places' },
  { word: 'hospital', wiki: 'Hospital', category: 'Places' },
  { word: 'library', wiki: 'Library', category: 'Places' },
  { word: 'market', wiki: 'Marketplace', category: 'Places', commons: 'Fruit Stall in Barcelona Market.jpg' },
  { word: 'park', wiki: 'Park', category: 'Places' },
  { word: 'farm', wiki: 'Farm', category: 'Places' },
  { word: 'bridge', wiki: 'Bridge', category: 'Places' },
  { word: 'road', wiki: 'Road', category: 'Places' },
  { word: 'castle', wiki: 'Castle', category: 'Places' },
  { word: 'car', wiki: 'Car', category: 'Places' },
  { word: 'bus', wiki: 'Bus', category: 'Places' },
  { word: 'train', wiki: 'Train', category: 'Places' },
  { word: 'bicycle', wiki: 'Bicycle', category: 'Places' },
  { word: 'airplane', wiki: 'Airplane', category: 'Places', article: 'an' },
  { word: 'boat', wiki: 'Boat', category: 'Places' },
  { word: 'ship', wiki: 'Ship', category: 'Places' },
  { word: 'tractor', wiki: 'Tractor', category: 'Places' },
  { word: 'helicopter', wiki: 'Helicopter', category: 'Places' },

  // -------------------------------------------------------------- Nature
  { word: 'sun', wiki: 'Sun', category: 'Nature' },
  { word: 'moon', wiki: 'Moon', category: 'Nature' },
  { word: 'star', wiki: 'Star', category: 'Nature', commons: 'Pleiades large.jpg' },
  { word: 'cloud', wiki: 'Cloud', category: 'Nature' },
  { word: 'rain', wiki: 'Rain', category: 'Nature', mass: true },
  { word: 'snow', wiki: 'Snow', category: 'Nature', commons: 'Winter forest after snow storm (40384754601).jpg', mass: true },
  { word: 'rainbow', wiki: 'Rainbow', category: 'Nature' },
  { word: 'tree', wiki: 'Tree', category: 'Nature' },
  { word: 'flower', wiki: 'Flower', category: 'Nature' },
  { word: 'leaf', wiki: 'Leaf', category: 'Nature' },
  { word: 'grass', wiki: 'Lawn', category: 'Nature', mass: true },
  { word: 'rock', wiki: 'Rock (geology)', category: 'Nature', commons: 'Smooth pebbles on the beach.jpg' },
  { word: 'mountain', wiki: 'Mountain', category: 'Nature' },
  { word: 'river', wiki: 'River', category: 'Nature' },
  { word: 'lake', wiki: 'Lake', category: 'Nature' },
  { word: 'ocean', wiki: 'Ocean', category: 'Nature' },
  { word: 'beach', wiki: 'Beach', category: 'Nature' },
  { word: 'forest', wiki: 'Forest', category: 'Nature' },
  { word: 'desert', wiki: 'Desert', category: 'Nature' },
  { word: 'island', wiki: 'Island', category: 'Nature', article: 'an' },
  { word: 'fire', wiki: 'Fire', category: 'Nature', mass: true },
  { word: 'sand', wiki: 'Sand', category: 'Nature', mass: true },
  { word: 'seashell', wiki: 'Seashell', category: 'Nature' },

  // ---------------------------------------------------------------- Body
  { word: 'hand', wiki: 'Hand', category: 'Body' },
  { word: 'foot', wiki: 'Foot', category: 'Body' },
  { word: 'eye', wiki: 'Eye', category: 'Body', article: 'an', commons: 'Human eye close up, anterior view.jpg' },
  { word: 'ear', wiki: 'Ear', category: 'Body', article: 'an' },
  { word: 'nose', wiki: 'Human nose', category: 'Body' },
  { word: 'mouth', wiki: 'Mouth', category: 'Body', commons: 'Lips 2023.jpg' },
  { word: 'tooth', wiki: 'Human tooth', category: 'Body' },
  { word: 'hair', wiki: 'Hair', category: 'Body', commons: 'A person with pink hair.jpg', mass: true },
  { word: 'arm', wiki: 'Arm', category: 'Body', article: 'an' },
  {
    word: 'leg',
    category: 'Body',
    // Commons has no clean, age-appropriate photo of a leg; this Flickr photo
    // is CC BY 2.0 and is credited in full on the picture-credits page.
    direct: {
      url: 'https://live.staticflickr.com/2711/4267332510_7229a0a729_b.jpg',
      author: 'Ted Eytan',
      license: 'CC BY 2.0',
      licenseUrl: 'https://creativecommons.org/licenses/by/2.0/',
      source: 'https://www.flickr.com/photos/taedc/4267332510',
    },
  },
  { word: 'finger', wiki: 'Finger', category: 'Body' },
  { word: 'face', wiki: 'Face', category: 'Body' },

  // ------------------------------------------------------- Food (part two)
  { word: 'avocado', wiki: 'Avocado', category: 'Food', article: 'an' },
  { word: 'coconut', wiki: 'Coconut', category: 'Food' },
  { word: 'blueberry', wiki: 'Blueberry', category: 'Food' },
  { word: 'raspberry', wiki: 'Raspberry', category: 'Food' },
  { word: 'plum', wiki: 'Plum', category: 'Food' },
  { word: 'kiwi', wiki: 'Kiwifruit', category: 'Food' },
  { word: 'melon', wiki: 'Melon', category: 'Food' },
  { word: 'cabbage', wiki: 'Cabbage', category: 'Food' },
  { word: 'lettuce', wiki: 'Lettuce', category: 'Food' },
  { word: 'cucumber', wiki: 'Cucumber', category: 'Food' },
  { word: 'pumpkin', wiki: 'Pumpkin', category: 'Food' },
  { word: 'mushroom', wiki: 'Mushroom', category: 'Food' },
  { word: 'pea', wiki: 'Pea', category: 'Food' },
  { word: 'bean', wiki: 'Bean', category: 'Food' },
  { word: 'garlic', wiki: 'Garlic', category: 'Food' },
  { word: 'pepper', wiki: 'Bell pepper', category: 'Food' },
  { word: 'butter', wiki: 'Butter', category: 'Food', mass: true },
  { word: 'soup', wiki: 'Soup', category: 'Food', mass: true },
  { word: 'sandwich', wiki: 'Sandwich', category: 'Food' },
  { word: 'pizza', wiki: 'Pizza', category: 'Food' },
  { word: 'pasta', wiki: 'Pasta', category: 'Food', mass: true },
  { word: 'chocolate', wiki: 'Chocolate', category: 'Food', mass: true },
  { word: 'sugar', wiki: 'Sugar', category: 'Food', mass: true },
  { word: 'salt', wiki: 'Salt', category: 'Food', mass: true },
  { word: 'water', wiki: 'Water', category: 'Food', mass: true },
  { word: 'juice', wiki: 'Juice', category: 'Food', mass: true },
  { word: 'tea', wiki: 'Tea', category: 'Food', mass: true },
  { word: 'popcorn', wiki: 'Popcorn', category: 'Food', mass: true },

  // ---------------------------------------------------- Animals (part two)
  { word: 'donkey', wiki: 'Donkey', category: 'Animals' },
  { word: 'camel', wiki: 'Camel', category: 'Animals' },
  { word: 'hippo', wiki: 'Hippopotamus', category: 'Animals' },
  { word: 'rhino', wiki: 'Rhinoceros', category: 'Animals' },
  { word: 'crocodile', wiki: 'Crocodile', category: 'Animals' },
  { word: 'lizard', wiki: 'Lizard', category: 'Animals' },
  { word: 'dolphin', wiki: 'Dolphin', category: 'Animals' },
  { word: 'whale', wiki: 'Whale', category: 'Animals' },
  { word: 'shark', wiki: 'Shark', category: 'Animals' },
  { word: 'octopus', wiki: 'Octopus', category: 'Animals', article: 'an' },
  { word: 'crab', wiki: 'Crab', category: 'Animals' },
  { word: 'starfish', wiki: 'Starfish', category: 'Animals' },
  { word: 'snail', wiki: 'Snail', category: 'Animals' },
  { word: 'spider', wiki: 'Spider', category: 'Animals' },
  { word: 'ant', wiki: 'Ant', category: 'Animals', article: 'an' },
  { word: 'ladybird', wiki: 'Coccinellidae', category: 'Animals' },
  { word: 'eagle', wiki: 'Eagle', category: 'Animals', article: 'an' },
  { word: 'peacock', wiki: 'Peafowl', category: 'Animals' },
  { word: 'swan', wiki: 'Swan', category: 'Animals' },
  { word: 'goose', wiki: 'Goose', category: 'Animals' },
  { word: 'turkey', wiki: 'Domestic turkey', category: 'Animals' },
  { word: 'pigeon', wiki: 'Columbidae', category: 'Animals' },
  { word: 'bat', wiki: 'Bat', category: 'Animals' },
  { word: 'wolf', wiki: 'Wolf', category: 'Animals' },
  { word: 'koala', wiki: 'Koala', category: 'Animals' },
  { word: 'seal', wiki: 'Pinniped', category: 'Animals' },
  { word: 'hedgehog', wiki: 'Hedgehog', category: 'Animals' },

  // -------------------------------------------------------------- Clothes
  { word: 'shirt', wiki: 'Shirt', category: 'Clothes' },
  { word: 't-shirt', wiki: 'T-shirt', category: 'Clothes' },
  { word: 'dress', wiki: 'Dress', category: 'Clothes' },
  { word: 'skirt', wiki: 'Skirt', category: 'Clothes' },
  { word: 'trousers', wiki: 'Trousers', category: 'Clothes', plural: true },
  { word: 'jeans', wiki: 'Jeans', category: 'Clothes', plural: true },
  { word: 'jacket', wiki: 'Jacket', category: 'Clothes' },
  { word: 'coat', wiki: 'Coat (clothing)', category: 'Clothes' },
  { word: 'sweater', wiki: 'Sweater', category: 'Clothes' },
  { word: 'hat', wiki: 'Hat', category: 'Clothes' },
  { word: 'cap', wiki: 'Baseball cap', category: 'Clothes' },
  { word: 'scarf', wiki: 'Scarf', category: 'Clothes' },
  { word: 'glove', wiki: 'Glove', category: 'Clothes' },
  { word: 'sock', wiki: 'Sock', category: 'Clothes' },
  { word: 'shoe', wiki: 'Shoe', category: 'Clothes' },
  { word: 'boot', wiki: 'Boot', category: 'Clothes' },
  { word: 'sandal', wiki: 'Sandal', category: 'Clothes' },
  { word: 'belt', wiki: 'Belt (clothing)', category: 'Clothes' },
  { word: 'button', wiki: 'Button', category: 'Clothes' },
  { word: 'pocket', wiki: 'Pocket', category: 'Clothes' },
  { word: 'ring', wiki: 'Ring (jewellery)', category: 'Clothes' },
  { word: 'watch', wiki: 'Watch', category: 'Clothes' },
  { word: 'glasses', wiki: 'Glasses', category: 'Clothes', plural: true },
  { word: 'apron', wiki: 'Apron', category: 'Clothes', article: 'an' },

  // ------------------------------------------------------------- Vehicles
  { word: 'truck', wiki: 'Truck', category: 'Vehicles' },
  { word: 'van', wiki: 'Van', category: 'Vehicles' },
  { word: 'taxi', wiki: 'Taxi', category: 'Vehicles' },
  { word: 'motorcycle', wiki: 'Motorcycle', category: 'Vehicles' },
  { word: 'scooter', wiki: 'Scooter (motorcycle)', category: 'Vehicles' },
  { word: 'ambulance', wiki: 'Ambulance', category: 'Vehicles', article: 'an' },
  { word: 'fire engine', wiki: 'Fire engine', category: 'Vehicles' },
  { word: 'police car', wiki: 'Police car', category: 'Vehicles' },
  { word: 'submarine', wiki: 'Submarine', category: 'Vehicles' },
  { word: 'canoe', wiki: 'Canoe', category: 'Vehicles' },
  { word: 'ferry', wiki: 'Ferry', category: 'Vehicles' },
  { word: 'rocket', wiki: 'Rocket', category: 'Vehicles' },
  { word: 'hot air balloon', wiki: 'Hot air balloon', category: 'Vehicles' },
  { word: 'sled', wiki: 'Sled', category: 'Vehicles' },
  { word: 'wheel', wiki: 'Wheel', category: 'Vehicles' },
  { word: 'tyre', wiki: 'Tire', category: 'Vehicles' },

  // ---------------------------------------------------------------- Sport
  { word: 'ball', wiki: 'Ball', category: 'Sport' },
  { word: 'football', wiki: 'Ball (association football)', category: 'Sport' },
  { word: 'cricket bat', wiki: 'Cricket bat', category: 'Sport', commons: 'A Modern Cricket Bat.jpg' },
  { word: 'basketball', wiki: 'Basketball (ball)', category: 'Sport' },
  { word: 'tennis racket', wiki: 'Racket (sports equipment)', category: 'Sport' },
  { word: 'badminton', wiki: 'Badminton', category: 'Sport' },
  { word: 'swimming', wiki: 'Swimming (sport)', category: 'Sport', mass: true },
  { word: 'running', wiki: 'Running', category: 'Sport', mass: true },
  { word: 'cycling', wiki: 'Cycling', category: 'Sport', mass: true },
  { word: 'skating', wiki: 'Ice skating', category: 'Sport', mass: true },
  { word: 'skipping rope', wiki: 'Skipping rope', category: 'Sport' },
  { word: 'kite', wiki: 'Kite', category: 'Sport' },
  { word: 'swing', wiki: 'Swing (seat)', category: 'Sport' },
  { word: 'slide', wiki: 'Playground slide', category: 'Sport' },
  { word: 'medal', wiki: 'Medal', category: 'Sport' },
  { word: 'trophy', wiki: 'Trophy', category: 'Sport' },

  // ---------------------------------------------------------------- Music
  { word: 'drum', wiki: 'Drum', category: 'Music' },
  { word: 'guitar', wiki: 'Guitar', category: 'Music' },
  { word: 'piano', wiki: 'Piano', category: 'Music' },
  { word: 'violin', wiki: 'Violin', category: 'Music' },
  { word: 'flute', wiki: 'Flute', category: 'Music' },
  { word: 'trumpet', wiki: 'Trumpet', category: 'Music' },
  { word: 'harmonica', wiki: 'Harmonica', category: 'Music' },
  { word: 'tabla', wiki: 'Tabla', category: 'Music' },
  { word: 'sitar', wiki: 'Sitar', category: 'Music' },
  { word: 'microphone', wiki: 'Microphone', category: 'Music' },
  { word: 'headphones', wiki: 'Headphones', category: 'Music', plural: true },
  { word: 'radio', wiki: 'Radio receiver', category: 'Music' },

  // ----------------------------------------------------------------- Jobs
  { word: 'doctor', wiki: 'Physician', category: 'Jobs' },
  { word: 'nurse', wiki: 'Nursing', category: 'Jobs' },
  { word: 'teacher', wiki: 'Teacher', category: 'Jobs' },
  { word: 'farmer', wiki: 'Farmer', category: 'Jobs' },
  { word: 'chef', wiki: 'Chef', category: 'Jobs' },
  { word: 'baker', wiki: 'Baker', category: 'Jobs' },
  { word: 'firefighter', wiki: 'Firefighter', category: 'Jobs' },
  { word: 'police officer', wiki: 'Police officer', category: 'Jobs' },
  { word: 'pilot', wiki: 'Aviator', category: 'Jobs' },
  { word: 'astronaut', wiki: 'Astronaut', category: 'Jobs', article: 'an' },
  { word: 'artist', wiki: 'Artist', category: 'Jobs', article: 'an' },
  { word: 'carpenter', wiki: 'Carpenter', category: 'Jobs' },
  { word: 'tailor', wiki: 'Tailor', category: 'Jobs' },
  { word: 'postman', wiki: 'Mail carrier', category: 'Jobs' },
  { word: 'dentist', wiki: 'Dentist', category: 'Jobs' },
  { word: 'scientist', wiki: 'Scientist', category: 'Jobs' },

  // -------------------------------------------------------------- Weather
  { word: 'sunshine', wiki: 'Sunlight', category: 'Weather', mass: true },
  { word: 'storm', wiki: 'Storm', category: 'Weather' },
  { word: 'lightning', wiki: 'Lightning', category: 'Weather', mass: true },
  { word: 'fog', wiki: 'Fog', category: 'Weather', mass: true },
  { word: 'wind', wiki: 'Wind', category: 'Weather', mass: true },
  { word: 'ice', wiki: 'Ice', category: 'Weather', mass: true },
  { word: 'hail', wiki: 'Hail', category: 'Weather', mass: true },
  { word: 'puddle', wiki: 'Puddle', category: 'Weather' },
  { word: 'sunset', wiki: 'Sunset', category: 'Weather' },
  { word: 'sunrise', wiki: 'Sunrise', category: 'Weather' },

  // ---------------------------------------------------- School (part two)
  { word: 'map', wiki: 'Map', category: 'School' },
  { word: 'flag', wiki: 'Flag', category: 'School' },
  { word: 'calendar', wiki: 'Calendar', category: 'School' },
  { word: 'envelope', wiki: 'Envelope', category: 'School', article: 'an' },
  { word: 'stamp', wiki: 'Postage stamp', category: 'School' },
  { word: 'newspaper', wiki: 'Newspaper', category: 'School' },
  { word: 'magnet', wiki: 'Magnet', category: 'School' },
  { word: 'microscope', wiki: 'Microscope', category: 'School' },
  { word: 'computer', wiki: 'Personal computer', category: 'School' },
  { word: 'keyboard', wiki: 'Computer keyboard', category: 'School' },

  // ------------------------------------------------------ Home (part two)
  { word: 'candle', wiki: 'Candle', category: 'Home' },
  { word: 'blanket', wiki: 'Blanket', category: 'Home' },
  { word: 'pillow', wiki: 'Pillow', category: 'Home' },
  { word: 'curtain', wiki: 'Curtain', category: 'Home' },
  { word: 'carpet', wiki: 'Carpet', category: 'Home' },
  { word: 'stairs', wiki: 'Stairs', category: 'Home', plural: true },
  { word: 'roof', wiki: 'Roof', category: 'Home' },
  { word: 'garden', wiki: 'Garden', category: 'Home' },
  { word: 'fence', wiki: 'Fence', category: 'Home' },
  { word: 'ladder', wiki: 'Ladder', category: 'Home' },
  { word: 'hammer', wiki: 'Hammer', category: 'Home' },
  { word: 'saw', wiki: 'Saw', category: 'Home' },
  { word: 'nail', wiki: 'Nail (fastener)', category: 'Home' },
  { word: 'rope', wiki: 'Rope', category: 'Home' },
  { word: 'bucket', wiki: 'Bucket', category: 'Home' },
  { word: 'kettle', wiki: 'Kettle', category: 'Home' },
  { word: 'fridge', wiki: 'Refrigerator', category: 'Home' },
  { word: 'oven', wiki: 'Oven', category: 'Home', article: 'an' },
  { word: 'fan', wiki: 'Fan (machine)', category: 'Home' },

  // ----------------------------------------------------------------- Toys
  { word: 'ball pit', wiki: 'Ball pit', category: 'Toys' },
  { word: 'doll', wiki: 'Doll', category: 'Toys' },
  { word: 'teddy bear', wiki: 'Teddy bear', category: 'Toys' },
  { word: 'puzzle', wiki: 'Jigsaw puzzle', category: 'Toys' },
  { word: 'blocks', wiki: 'Toy block', category: 'Toys', plural: true },
  { word: 'marble', wiki: 'Marble (toy)', category: 'Toys' },
  { word: 'yo-yo', wiki: 'Yo-yo', category: 'Toys' },
  { word: 'top', wiki: 'Spinning top', category: 'Toys' },
  { word: 'robot', wiki: 'Robot', category: 'Toys' },
  { word: 'balloon', wiki: 'Toy balloon', category: 'Toys' },
  { word: 'chess', wiki: 'Chess', category: 'Toys', mass: true },
  { word: 'dice', wiki: 'Dice', category: 'Toys', plural: true },

  // --------------------------------------------------------------- Shapes
  { word: 'circle', wiki: 'Circle', category: 'Shapes' },
  { word: 'square', wiki: 'Square', category: 'Shapes' },
  { word: 'triangle', wiki: 'Triangle', category: 'Shapes' },
  { word: 'rectangle', wiki: 'Rectangle', category: 'Shapes' },
  { word: 'star shape', wiki: 'Star polygon', category: 'Shapes' },
  { word: 'heart', wiki: 'Heart symbol', category: 'Shapes' },
  { word: 'cube', wiki: 'Cube', category: 'Shapes' },
  { word: 'sphere', wiki: 'Sphere', category: 'Shapes' },
  { word: 'spiral', wiki: 'Spiral', category: 'Shapes' },
  { word: 'arrow', wiki: 'Arrow (symbol)', category: 'Shapes', article: 'an' },

  // ---------------------------------------------------- Nature (part two)
  { word: 'volcano', wiki: 'Volcano', category: 'Nature' },
  { word: 'waterfall', wiki: 'Waterfall', category: 'Nature' },
  { word: 'cave', wiki: 'Cave', category: 'Nature' },
  { word: 'valley', wiki: 'Valley', category: 'Nature' },
  { word: 'field', wiki: 'Field (agriculture)', category: 'Nature' },
  { word: 'root', wiki: 'Root', category: 'Nature' },
  { word: 'branch', wiki: 'Branch', category: 'Nature' },
  { word: 'seed', wiki: 'Seed', category: 'Nature' },
  { word: 'cactus', wiki: 'Cactus', category: 'Nature' },
  { word: 'palm tree', wiki: 'Arecaceae', category: 'Nature' },
  { word: 'rose', wiki: 'Rose', category: 'Nature' },
  { word: 'sunflower', wiki: 'Common sunflower', category: 'Nature' },
  { word: 'feather', wiki: 'Feather', category: 'Nature' },
  { word: 'nest', wiki: 'Bird nest', category: 'Nature' },
  { word: 'honeycomb', wiki: 'Honeycomb', category: 'Nature' },

  // ---------------------------------------------------- Places (part two)
  { word: 'temple', wiki: 'Temple', category: 'Places' },
  { word: 'mosque', wiki: 'Mosque', category: 'Places' },
  { word: 'church', wiki: 'Church (building)', category: 'Places' },
  { word: 'museum', wiki: 'Museum', category: 'Places' },
  { word: 'airport', wiki: 'Airport', category: 'Places', article: 'an' },
  { word: 'station', wiki: 'Train station', category: 'Places' },
  { word: 'harbour', wiki: 'Harbor', category: 'Places' },
  { word: 'lighthouse', wiki: 'Lighthouse', category: 'Places' },
  { word: 'tower', wiki: 'Tower', category: 'Places' },
  { word: 'zoo', wiki: 'Zoo', category: 'Places' },
  { word: 'restaurant', wiki: 'Restaurant', category: 'Places' },
  { word: 'bakery', wiki: 'Bakery', category: 'Places' },
  { word: 'playground', wiki: 'Playground', category: 'Places' },
  { word: 'city', wiki: 'City', category: 'Places' },
  { word: 'village', wiki: 'Village', category: 'Places' },

  // -------------------------------------------------------------- Colors
  { word: 'red', wiki: 'Red', category: 'Colors' },
  { word: 'blue', wiki: 'Blue', category: 'Colors' },
  { word: 'green', wiki: 'Green', category: 'Colors' },
  { word: 'yellow', wiki: 'Yellow', category: 'Colors' },
  { word: 'purple', wiki: 'Purple', category: 'Colors' },
  { word: 'pink', wiki: 'Pink', category: 'Colors' },
  { word: 'brown', wiki: 'Brown', category: 'Colors' },
  { word: 'black', wiki: 'Black', category: 'Colors' },
  { word: 'white', wiki: 'White', category: 'Colors' },
  { word: 'grey', wiki: 'Grey', category: 'Colors' },
];

export const categories = [
  'Food', 'Animals', 'Clothes', 'School', 'Home', 'Toys', 'Places', 'Vehicles',
  'Nature', 'Weather', 'Sport', 'Music', 'Jobs', 'Body', 'Shapes', 'Colors',
];
